build.gradle, src/main/java/io/reactivesocket/CancellationToken.java, src/main/java/io/reactivesocket/DuplexConnection.java, src/main/java/io/reactivesocket/Message.java, src/main/java/io/reactivesocket/MessageType.java, src/main/java/io/reactivesocket/ReactiveSocketServerProtocol.java, src/test/java/io/reactivesocket/MessageTest.java, src/test/java/io/reactivesocket/ReactiveSocketServerProtocolTest.java, src/test/java/io/reactivesocket/TestConnection.java
This is exploratory and still using ASCII rather than binary.
=> ServerProtocol with UnitTests

src/main/java/io/reactivesocket/DuplexConnection.java, src/main/java/io/reactivesocket/Message.java, src/main/java/io/reactivesocket/MessageType.java, src/main/java/io/reactivesocket/ReactiveSocketClientProtocol.java, src/main/java/io/reactivesocket/ReactiveSocketServerProtocol.java, src/main/java/io/reactivesocket/RequestHandler.java, src/test/java/io/reactivesocket/ClientServerInteractionTest.java, src/test/java/io/reactivesocket/MessageTest.java, src/test/java/io/reactivesocket/ReactiveSocketClientProtocolTest.java, src/test/java/io/reactivesocket/ReactiveSocketServerProtocolTest.java, src/test/java/io/reactivesocket/TestConnection.java
- made write support async with `write(Publisher<Message>)` signature
- move to MessageTypes defined in draft of protocol
- separated the 4 request handlers
- added client protocol implementation
- everything is still String based while waiting on binary encoding and decision of what byte abstraction we will use
=> Client/Server Protocol

src/main/java/io/reactivesocket/FairLeaseGovernor.java, src/main/java/io/reactivesocket/LeaseGovernor.java, src/main/java/io/reactivesocket/NullLeaseGovernor.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/UnlimitedLeaseGovernor.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/RequesterResponderInteractionTest.java, src/test/java/io/reactivesocket/TestConnection.java, src/test/java/io/reactivesocket/internal/ResponderTest.java
A Requester who create a ReactiveSocket with the HONOR_LEASE bit, will now have
to wait for a LEASE from a server before beeing able to send any request.
I added some very simple lease distribution strategies for testing purposes,
they are nowhere near the one that we'll use in production.
I also refactored the unit-test to use JUnit Theory, which now test the
ReactiveSocket with multiple combinations of parameters.
=> Introduce the LEASE mechanism.

src/main/java/io/reactivesocket/FairLeaseGovernor.java, src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/LeaseGovernor.java, src/main/java/io/reactivesocket/NullLeaseGovernor.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/UnlimitedLeaseGovernor.java, src/main/java/io/reactivesocket/exceptions/LeaseException.java, src/main/java/io/reactivesocket/internal/LeaseFrameFlyweight.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/FrameTest.java, src/test/java/io/reactivesocket/LeaseTest.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java
This allow to have implementation of the Requester that still send
message even outside of a valid lease (not recommended, but it could
be useful in specific case like full cluster down).
Lease TTL and Tickets have been converted to 32bits + the time
unit is now millisecond.
=> Remove the check for valid from the Requester to the Responder.

src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/RequesterResponderInteractionTest.java, src/test/java/io/reactivesocket/TestFlowControlRequestN.java, src/test/java/io/reactivesocket/internal/RequesterTest.java, src/test/java/io/reactivesocket/internal/ResponderTest.java, src/test/java/io/reactivesocket/internal/UnicastSubjectTest.java
Making `request(n)` behavior thread-safe with the use of `compareAndSet` and making mutable references `volatile`.
=> Thread Safety

src/main/java/io/reactivesocket/internal/EmptyDisposable.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/main/java/io/reactivesocket/observable/Disposable.java, src/main/java/io/reactivesocket/observable/Observable.java, src/main/java/io/reactivesocket/observable/Observer.java, src/main/java/io/reactivesocket/observable/README.md, src/perf/java/io/reactivesocket/perfutil/PerfTestConnection.java, src/perf/java/io/reactivesocket/perfutil/PerfUnicastSubjectNoBackpressure.java, src/test/java/io/reactivesocket/TestConnection.java
I think it might be wrong to represent `getInput` as a `Publisher` since it can't respond to backpressure. 
Since we don't have concrete types (RxJava v1/v2) or anything else to represent this, I am (hopefully temporarily) creating `Observable`/`Observer`/`Disposable` interfaces to represent the `getInput`.
=> DuplexConnection.getInput as Observable

src/test/java/io/reactivesocket/RequesterResponderInteractionTest.java, src/test/java/io/reactivesocket/TestConnection.java, src/test/java/io/reactivesocket/internal/RequesterTest.java, src/test/java/io/reactivesocket/internal/ResponderTest.java
Replace use of Subjects with simple event propagation. The RxJava v2 subjects are causing me grief, so I'm eliminating their use for now.
Also, this removes concurrency for now.
=> new TestConnection

src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/TestConnection.java
This adds back concurrency to TestConnection.
The threads for client/server, and main thread where requests originate from, are shown in these logs.
```
CLIENT ==> Writes from client->server: Frame[0] => Stream ID: 0 Type: SETUP Payload Data:    Written from Thread[Time-limited test,5,FailOnTimeoutGroup]
SERVER <== Input from client->server: Frame[0] => Stream ID: 0 Type: SETUP Payload Data:    Read on Thread[RxNewThreadScheduler-1,5,FailOnTimeoutGroup]
CLIENT ==> Writes from client->server: Frame[0] => Stream ID: 2 Type: REQUEST_RESPONSE Payload Data: data: "hello"   Written from Thread[Time-limited test,5,FailOnTimeoutGroup]
SERVER <== Input from client->server: Frame[0] => Stream ID: 2 Type: REQUEST_RESPONSE Payload Data: data: "hello"   Read on …
```
=> Add Concurrency Back to TestConnection

src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/internal/ErrorFrameFlyweight.java, src/main/java/io/reactivesocket/internal/ThreadSafeFramePool.java, src/test/java/io/reactivesocket/TestConnection.java
=> cleanup of some frame pooling

src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/SerializedEventBus.java, src/test/java/io/reactivesocket/TestConnection.java, src/test/java/io/reactivesocket/TestConnectionWithControlledRequestN.java, src/test/java/io/reactivesocket/TestTransportRequestN.java
Stop ignoring the `request(n)` of the transport layer.
=> Compose Request(n) – Transport/Application

src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/internal/UnicastSubjectTest.java
Check the value of request-n before asking the requester n-1 items,
it was possible to request 0 items.
=> Responder: fix bug in Channel request-n

src/main/java/io/reactivesocket/internal/rx/EmptyDisposable.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1444 - "public static" fields should be constant
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1444
Please let me know if you have any questions.
Faisal Hameed
=> Code quality fix -  "public static" fields should be constant

src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/FrameType.java, src/main/java/io/reactivesocket/exceptions/Exceptions.java, src/main/java/io/reactivesocket/internal/PublisherUtils.java, src/main/java/io/reactivesocket/internal/frame/ByteBufferUtil.java, src/main/java/io/reactivesocket/internal/frame/ErrorFrameFlyweight.java, src/main/java/io/reactivesocket/internal/frame/FrameHeaderFlyweight.java, src/main/java/io/reactivesocket/internal/frame/KeepaliveFrameFlyweight.java, src/main/java/io/reactivesocket/internal/frame/LeaseFrameFlyweight.java, src/main/java/io/reactivesocket/internal/frame/RequestFrameFlyweight.java, src/main/java/io/reactivesocket/internal/frame/RequestNFrameFlyweight.java, src/main/java/io/reactivesocket/internal/frame/SetupFrameFlyweight.java, src/test/java/io/reactivesocket/TestUtil.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Faisal Hameed
=> Code quality fix - Utility classes should not have public constructors.

src/main/java/io/reactivesocket/exceptions/Exceptions.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/main/java/io/reactivesocket/internal/rx/CompositeDisposable.java, src/main/java/io/reactivesocket/lease/FairLeaseGovernor.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1854 - Dead stores should be removed. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
Faisal Hameed
=> Code quality fix - Dead stores should be removed.

src/main/java/io/reactivesocket/ConnectionSetupPayload.java, src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/FrameType.java, src/main/java/io/reactivesocket/RequestHandler.java, src/main/java/io/reactivesocket/internal/PublisherUtils.java, src/main/java/io/reactivesocket/internal/UnicastSubject.java, src/main/java/io/reactivesocket/internal/frame/FrameHeaderFlyweight.java, src/main/java/io/reactivesocket/internal/frame/PayloadFragmenter.java, src/perf/java/io/reactivesocket/perfutil/PerfUnicastSubjectNoBackpressure.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/TestTransportRequestN.java
This pull request is focused on resolving occurrences of Sonar rules 
squid:S2293 - The diamond operator ("<>") should be used.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2293
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
Faisal Hameed
=> General code quality fix-1

src/main/java/io/reactivesocket/DefaultReactiveSocket.java, src/main/java/io/reactivesocket/DuplexConnection.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java
As a callback that is called when a reactive socket is closed.
=> adding callback on shutdown

src/main/java/io/reactivesocket/DefaultReactiveSocket.java, src/main/java/io/reactivesocket/DuplexConnection.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/ReactiveSocketConnector.java, src/main/java/io/reactivesocket/ReactiveSocketFactory.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/util/ReactiveSocketProxy.java, src/perf/java/io/reactivesocket/perfutil/PerfTestConnection.java, src/test/java/io/reactivesocket/TestConnection.java
**Problem**
The DuplexConnection class doesn't expose any way to probe its state,
this is somewhat problematic and doesn't fit well in the current
model where the availability is the composable way of chaining state.
The ReactiveSocketFactory create a ReactiveSocket from an `address`
(currently SocketAddress). There are places in the code where the concept
of address is not needed and it leads to implicit dependency on it.
**Solution**
Add a `double availability()` method to the DuplexConnection interface,
most implementation of this method will be straightforward (just
returning 0.0 if the underlying resource is unavailable, 1.0 otherwise).
Split the concept of ReactiveSocketFactory in two, the Factory and the
Connector. The Connector is responsible for creating the ReactiveSocket
from …
=> Introduce Connector and availability for Connection

reactivesocket-transport-tcp/src/examples/java/io/reactivesocket/transport/tcp/EchoServerHandler.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/server/ReactiveSocketServerHandler.java, reactivesocket-transport-tcp/src/test/java/io/reactivesocket/transport/tcp/ClientServerTest.java, reactivesocket-transport-tcp/src/test/java/io/reactivesocket/transport/tcp/Ping.java, reactivesocket-transport-tcp/src/test/java/io/reactivesocket/transport/tcp/Pong.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/server/ReactiveSocketServerHandler.java, reactivesocket-transport-websocket/src/test/java/io/reactivesocket/transport/websocket/Ping.java, reactivesocket-transport-websocket/src/test/java/io/reactivesocket/transport/websocket/Pong.java
**Problem**
There's a memory leak in `ReactiveSocketServerHandler`, it keep adding entries
in the `duplexConnections` map but never remove them.
**Solution**
Instead of having only one `ReactiveSocketServerHandler`, and manage resources
manually, we let Netty allocate one instance per Channel. Then no resource
management is necessary.
**Modifications**
I refactored all the uages of `ReactiveSocketServerHandler` whithout changing
the logic. I also got rid of the method
```
public void channelReadComplete(ChannelHandlerContext ctx) {
ctx.flush();
}
```
since we only use `writeAndFlush` in the DuplexConnection (we're sure there's
nothing to flush).
=> Refactor ReactiveSocketServerHandler to be not shareable.

reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/ClientTcpDuplexConnection.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/TcpReactiveSocketConnector.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/ClientWebSocketDuplexConnection.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/WebSocketReactiveSocketConnector.java
**Problem**
The initialization of the Publisher chain is usually started from
a `onSubscribe` call which was lacking in the transport implementations
we care about.
**Solution**
Add a call to `onSubscribe` with an EmptySubscriber because there's no
notion of back-pressure here, we only eagerly deliver one `ReactiveSocket`.
=> Correctly wire subscription from Transport Connectors.

reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/ClientTcpDuplexConnection.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/ClientWebSocketDuplexConnection.java
**Problem**
A Publisher may not have been initialized when a DuplexConnection failed during
the connection establishement. (e.g. connection reset by peer)
**Solution**
Do the subscription as soon as Netty complete, regarding of the result
of the ConnectFuture.
=> Fix subscription in DuplexConnection.

reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/TcpReactiveSocketConnector.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/WebSocketReactiveSocketConnector.java
**Problem**
Instead of manually requesting in the `onSubscribe`, it's better
to actually pass the `Subscription` to the `Subscriber`.
The *Connector code was a little bit confusing because the `Subscriber`
like the `Subscription` were names `s`.
**Solution**
Rename the `Subscriber` -> `subscriber`, and pass the subscription.
=> Wire `onSubscribe` in *Connector.

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java
**Problem**
There are bugs related to Backup-Request/Retries subscription.
The remaining part of the code is ok.
**Solution**
Disable the code in the ClientBuilder.
=> Disable Backup-Request / Retries.

reactivesocket-core/src/main/java/io/reactivesocket/DefaultReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/KnownErrorFilter.java
Since `ReactiveSocket` reads and writes from a transport connection, it is completely expected that at some point the underlying connection may have been severed. In such a case, both the read and write will fail on the connection. This pollutes logs of applications that directly log the error stream (as expected).
Since, this is kind of an "expected" exception, there is no point to send this to the error stream.
This change adds a filter to the error stream to filter any known exceptions (as of today, it is only `ClosedChannelException`)
_PS: We currently do not unsubscribe from the input (and stop writing) when `ReactiveSocket` is explicitly closed. This change does not mean, we do not clean that up._
=> Ignoring `ClosedChannelException` from the error stream.

reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/server/TcpReactiveSocketServer.java
**Problem**
It is impossible to specify the network interface to use when starting a server.
This can be problematic when we want to design test that run in restricted
environment (e.g. CI).
**Solution**
Create an overload of `TcpReactiveSocketServer.create` that accept a
SocketAddress instead of just the port.
=> Add an overload of `TcpReactiveSocketServer.create` with SocketAddress.

reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/ClientWebSocketDuplexConnection.java
**Problem**
The websocket DuplexConnection doesn't initialize the Publisher chain
in every cases.
**Solution**
Move the initialization code `onSubscribe` up, and also rename the subscriber
`subscriber` instead of `s` to avoid confusion with the `Subscription`.
=> Fix subscription for Websocket transport

reactivesocket-core/src/main/java/io/reactivesocket/DefaultReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Requester.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Responder.java
**Problem**
When we close a ReactiveSocket, it closes the underlying DuplexConnection
which trigger an unnecessary onError on the Requester/Responder.
**Solution**
Store the disposable of the DuplexConnection subscription as an instance
variable, and dispose it before closing the DuplexConnection.
**Modification**
I also added a `name` method in Requester/Responder to simplify debugging
code where we have client and server in the same JVM.
It now shows which Requester/Responder is generating an error, the client's
one or the server's one.
=> Unsubscribe from the connection before `shutdown` the RS.

reactivesocket-core/src/main/java/io/reactivesocket/internal/Responder.java
In some cases, `Responder` was converting an `onError()` to `onNext(Frame.Error)` but was not sending an `onComplete()` after the `onNext()`.
This causes the `subscriber` to wait for a terminal event, which never arrives, or if it arrives, does not find the `streamId` to be valid since the code was invoking `cleanUp()`.
This although subtle, but causes memory build up as the `Subscriber` in the case of a server, is the subscriber which is writing the response. If the response does not complete, all state associated with the request is kept alive forever.
Call `onComplete()` after sending an error frame.
This code does not call `cancel()` after `onComplete()` as reactive streams spec does not mandate cancellation post a terminal event, unlike `RxJava`.
No more memory leak!
=> Completing subscriber after sending error frame (caused memory leak).

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/Exceptions.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/PublisherUtils.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Requester.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ByteBufferUtil.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/SetupFrameFlyweight.java, reactivesocket-core/src/perf/java/io/reactivesocket/FramePerf.java, reactivesocket-core/src/perf/java/io/reactivesocket/ReactiveSocketPerf.java, reactivesocket-core/src/test/java/io/reactivesocket/FrameTest.java, reactivesocket-core/src/test/java/io/reactivesocket/TestUtil.java, reactivesocket-mime-types/src/main/java/io/reactivesocket/mimetypes/internal/cbor/MetadataCodec.java, reactivesocket-mime-types/src/test/java/io/reactivesocket/mimetypes/internal/MetadataRule.java, reactivesocket-mime-types/src/test/java/io/reactivesocket/mimetypes/internal/cbor/CborUtf8StringCodecTest.java, reactivesocket-mime-types/src/test/java/io/reactivesocket/mimetypes/internal/cbor/MetadataCodecTest.java, reactivesocket-test/src/main/java/io/reactivesocket/test/TestUtil.java, reactivesocket-transport-tcp/src/test/java/io/reactivesocket/transport/tcp/Ping.java, reactivesocket-transport-websocket/src/test/java/io/reactivesocket/transport/websocket/Ping.java
I don't like this PR, so using it for discussion.
The spec says
> Encoding MIME Type: MIME Type for encoding of Data and Metadata. This MAY be a US-ASCII string that includes the Internet media type specified in RFC 2045. Many are registered with IANA such as CBOR. Suffix rules MAY be used for handling layout. For example, application/x.netflix+cbor or application/x.reactivesocket+cbor or application/x.netflix+json. The string may or may not be null terminated.
Does this actually mean:  "This MAY be a Internet media type specified in RFC 2045.  If present, the value MUST be US-ASCII.".  If it can be UTF-8 then string.length() may not be the byte length.
Also can we change the spec to say that the string MUST NOT be null terminated.  we need to string before creating strings.  I assume …
=> use charset consistently

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Requester.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/PayloadBuilder.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/PayloadFragmenter.java, reactivesocket-core/src/test/java/io/reactivesocket/FrameTest.java
Replace use of capacity which is only appropriate if you know exactly what the client has given you (a whole ByteBuffer representing the relevant data).  Uses remaining instead which assumes you trust your caller has given you a buffer that won't be change during the method call, but uses position and limit to support sliced buffers.
=> use remaining instead of capacity generally

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java
***Problem***
The loadbalancer doesn't find an active socket to use, it doesn't do anything
about it.
***Solution***
When the "power of two choices" algorithm failed to find a socket
after `EFFORT=5` tries, asynchronously add a new socket.
=> Loadbalancer: Add a ReactiveSocket when none is available.

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java
***Problem***
Hard-coded values in the code.
***Solution***
Move those hard-coded values into static members.
Initial inter-arrival time is 1 seconds (The average time between
two requests for a particular server). This value will be updated continuously.
Inter-arrival factor is now 500, after 500 times the default arrival time
we'll artificially decrease the load of a server so that it is selected
again. It solves the problem of server becoming temporarly latent, and
never being selected again.
=> Loadbalancer: Move inter-arrival time as constant.

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java
***Problem***
There's presently no way to disable timeouts/retries other than manually
composing the stack.
***Solution***
Default to disable any timeout in the ClientBuilder, remove completely retries.
Also remove unused fields `backupQuantile`, `counter` and `name`.
=> ClientBuilder: Disable default timeout, remove retries.

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java
***Problem***
The decision of reducing the aperture is based on the number of active sockets
+ the number of pending socket. This could be bad as we close sockets before
the pending ones connect, which should leave us under the aperture target.
***Solution***
Only reduce the aperture when the number of *active* socket is below the
aperture.
I also increase the aperture only when we have available factories in
order to reduce the debug log.
Reduce the log level of these logs to DEBUG.
=> Loadbalancer: Only reduce aperture based on active sockets (not pending)

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java, reactivesocket-discovery-eureka/src/main/java/io/reactivesocket/discovery/eureka/Eureka.java
`ClientBuilder.withSource()` takes an argument of `Publisher<Collection<T>>` which means it doesn't accept an `Publisher<List<T>>`.
`Eureka` is providing `Publisher<List<T>>` so it is incompatible with `ClientBuilder`
Changed `ClientBuilder.withSource()` to take `Publisher<? extends Collection<T>>`.
Also changed `Eureka` to return `Publisher<Collection<T>>` which is the correct thing to do as returning a `List` doesn't really make a difference.
=> Generics correctness in `ClientBuilder`

build.gradle
See more details explained in https://github.com/ReactiveSocket/reactivesocket-java/issues/138
I can elaborate on the complete story if you're keen on getting the whole story, however in general the simple rule is "ignore 1.0.0.final exists" :)
=> =build #138 Depend on the right RS version

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-core/src/main/java/io/reactivesocket/DefaultReactiveSocket.java
`FailingReactiveSocket` was invoking `Subscriber.onError()` without calling `onSubscribe()` which is invalid as per reactive-streams spec:
https://github.com/reactive-streams/reactive-streams-jvm#api-components
```
This means that onSubscribe is always signalled, followed by a possibly unbounded number of onNext signals (as requested by Subscriber) followed by an onError signal if there is a failure, or an onComplete signal when no more elements are available—all as long as the Subscription is not cancelled.
```
Modified to use `Publishers.error()` which follows the spec correctly.
Better adherence of spec, happy users :)
=> `FailingReactiveSocket` violates spec

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/BackupRequestSocket.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/DrainingSocket.java, reactivesocket-client/src/test/java/io/reactivesocket/client/TestingReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/DefaultReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/DuplexConnection.java, reactivesocket-core/src/main/java/io/reactivesocket/ReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/EmptySubject.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Requester.java, reactivesocket-core/src/main/java/io/reactivesocket/util/ReactiveSocketProxy.java, reactivesocket-core/src/perf/java/io/reactivesocket/perfutil/PerfTestConnection.java, reactivesocket-core/src/test/java/io/reactivesocket/LeaseTest.java, reactivesocket-core/src/test/java/io/reactivesocket/ReactiveSocketTest.java, reactivesocket-core/src/test/java/io/reactivesocket/TestConnection.java, reactivesocket-core/src/test/java/io/reactivesocket/TestFlowControlRequestN.java, reactivesocket-core/src/test/java/io/reactivesocket/TestTransportRequestN.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/EmptySubjectTest.java, reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/AvailabilityMetricReactiveSocket.java, reactivesocket-stats-servo/src/test/java/io/reactivesocket/loadbalancer/servo/ServoMetricsReactiveSocketTest.java, reactivesocket-transport-aeron/src/main/java/io/reactivesocket/aeron/client/AeronClientDuplexConnection.java, reactivesocket-transport-aeron/src/main/java/io/reactivesocket/aeron/client/AeronClientDuplexConnectionFactory.java, reactivesocket-transport-aeron/src/main/java/io/reactivesocket/aeron/server/AeronServerDuplexConnection.java, reactivesocket-transport-local/src/main/java/io/reactivesocket/local/LocalClientDuplexConnection.java, reactivesocket-transport-local/src/main/java/io/reactivesocket/local/LocalServerDuplexConection.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/TcpDuplexConnection.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/server/TcpReactiveSocketServer.java, reactivesocket-transport-tcp/src/test/java/io/reactivesocket/transport/tcp/ClientServerTest.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/client/ClientWebSocketDuplexConnection.java, reactivesocket-transport-websocket/src/main/java/io/reactivesocket/transport/websocket/server/ServerWebSocketDuplexConnection.java
As described in the issue #128, currently `ReactiveSocket` does not listen to `DuplexConnection` closures.
As suggested in the issue, removed `onShutdown()` and `shutdown()` methods, in favor of `close()` and `closeNotifier()` methods.
Added `close()` and `closeNotifier()` methods in `DuplexConnection`
=> Fixes issue #128 (Close on `DuplexConnection`)

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java, reactivesocket-client/src/test/java/io/reactivesocket/client/ClientBuilderTest.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/StressTest.java
***Problem***
The ClientBuilder `build` API return a ReactiveSocket.
This ReactiveSocket is returned while connections are still in establishing
mode, then it will fail until the connections established.
The current solution is to call `Unsafe.awaitAvailability` which is cluncky.
***Solution***
Create a more robust API that return a `Publisher<ReactiveSocket>`, it is now
obvious that the API is asynchronous.
I found a bug in `sourceToFactory`, where I was calling `subscriber.onSubscribe`
before initializing the `current` Map.
=> `ClientBuilder.build` is now asynchronous.

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java, reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/FailureAwareFactory.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/TimeoutFactory.java, reactivesocket-client/src/test/java/io/reactivesocket/client/FailureReactiveSocketTest.java, reactivesocket-client/src/test/java/io/reactivesocket/client/LoadBalancerTest.java, reactivesocket-core/src/main/java/io/reactivesocket/ReactiveSocketConnector.java, reactivesocket-core/src/main/java/io/reactivesocket/ReactiveSocketFactory.java, reactivesocket-core/src/main/java/io/reactivesocket/util/ReactiveSocketFactoryProxy.java
***Problem***
Since the refactoring of the `LoadBalancer` to use `List` instead of `Map`,
there's no need for a `remote` method that identify a remote server.
Furthermore, that's the only reason why LoadBalancer is generic.
***Solution***
Delete the method `ReactiveSocketFactory.remote()` as well as all the
references to it.
=> Remove `ReactiveSocketFactory.remote()`

reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ByteBufferUtil.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ErrorFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/KeepaliveFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/LeaseFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/PayloadBuilder.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/PayloadFragmenter.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/PayloadReassembler.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/RequestFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/RequestNFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/SetupFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ThreadLocalFramePool.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ThreadSafeFramePool.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/UnpooledFrame.java
***Problem***
There is an error in the Error frame, the error codes used for `APPLICATION_ERROR`,
`CONNECTION_ERROR`, `REJECTED`, `CANCELED` and `INVALID` were invalid.
***Solution***
Update the constants.
I don't think it requires doing any version bump, since the error code was not used
prior to #150.
I also took the oportunity to review the `frame` package and update it to the Java
code style.
=> Fix Error flags to match the spec + review the `frame` package.

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/rx/EmptySubscriber.java, reactivesocket-examples/src/test/java/io/reactivesocket/integration/IntegrationTest.java
***Problem***
Closing the loadbalancer doesn't properly subscribe to the `Publisher`s
returned by the `close()` methods of the underlying `ReactiveSocket`.
Thus, the close event is lost at the LoadBalancer level.
***Solution***
Properly subscribe to the close `Publisher`s and propagate the `onComplete`
events when all `ReactiveSocket` are closed. (I choose to ignore any exception
that happened during the close, i.e. only propagate 1 `onComplete`).
=> Loadbalancer: closing doesn't subscribe to the underlying

reactivesocket-core/src/main/java/io/reactivesocket/RequestHandler.java, reactivesocket-test/src/main/java/io/reactivesocket/test/TestRequestHandler.java, reactivesocket-transport-local/build.gradle
Making RequestHandler an interface rather than an abstract class for consistency with ReactiveSocket, makes it more flexible to extend.
=> Make RequestHandler an interface

reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/SetupFrameFlyweight.java
***Problem***
The flags used in the SETUP frame are different from the one defined in the specification.
They are defined as a byte (8bits) vs. a short (16bits)
(See https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#setup-frame)
***Solution***
Update the constant to the right value.
=> Fix SETUP flags according to the spec

reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ErrorFrameFlyweight.java
It should have been fixed in #151, that was an oversight from my part.
=> Fix REJECTED error code to match the spec.

reactivesocket-core/src/main/java/io/reactivesocket/internal/PublisherUtils.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Responder.java
***Problem***
There's currently a leak of responder reference in the `LeaseGovernor`,
upon disconnection, the `Responder` is not removing its reference from the
Governor.
***Solution***
On cancel/disconnection/exception the Responder is now removing itself.
I tested that with the JS and Java client.
The `TestConnection` doesn't make disconnection testing possible with the
present code, I'll improve this in another commit.
I also clean-up the code-style of PublisherUtils.
=> Fix Responder leak in LeaseGovernor

reactivesocket-core/src/main/java/io/reactivesocket/lease/FairLeaseGovernor.java
***Problem***
The `FairLeaseGovernor` currently distributes its budget among the connected
peers. It does so by dividing its total budget by the number of connected clients,
and add the remaining budget (`n`) among the first `n` responders.
This is fine when the budget is far greater than the number of clients, but in the
opposite situation, it leads to client starving, as the budget is always distributed
in the same order.
***Solution***
Shuffle the list of client prior to distributing the budget.
=> More fairness for the FairLeaseGovernor

reactivesocket-core/src/main/java/io/reactivesocket/exceptions/ApplicationException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/CancelException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/ConnectionException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/InvalidRequestException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/RejectedException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/SetupException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/TimeoutException.java, reactivesocket-core/src/main/java/io/reactivesocket/exceptions/TransportException.java
Throwable is awkward e.g.
```
java.lang.RuntimeException: io.reactivesocket.exceptions.ApplicationException: St13runtime_error: XXX
at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
at rx.Completable.await(Completable.java:1051)
at io.reactivesocket.cli.Main.run(Main.java:87)
at io.reactivesocket.cli.Main.main(Main.java:182)
Caused by: io.reactivesocket.exceptions.ApplicationException: St13runtime_error: XXX
```
=> use RuntimeException

reactivesocket-core/src/main/java/io/reactivesocket/internal/frame/ErrorFrameFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/RequesterTest.java
For discussion:
I'd argue this is the right code because its the behaviour you get with
requestHandlerBuilder.withRequestResponse(payload ->
RxReactiveStreams.toPublisher(Observable.error(new Exception("server failure")))).build();
We can't know all errors ahead of time, and I don't think we should ask users to map things to ApplicationError.
=> more app errors please

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/ClientServerInputMultiplexer.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/FairLeaseDistributor.java
`ClientServerInputMultiplexer` is not sending any stream 0 frames to `ClientReactiveSocket`. Since, leases come on stream 0, clients were not receiving the leases.
Modified `ClientServerInputMultiplexer` to send stream 0 frames to both sockets (since both ends receive frames on stream 0) and let them decide which ones are useful for them.
Also modified `FairLeaseDistributor` to subscribe to ticks after the first socket is registered. This provides predictable behavior w.r.t the first lease distribution i.e. if the lease ticks start on subscription, generally the first lease is missed by the first socket.
Clients now receive leases.
=> Client is not receiving leases

reactivesocket-core/src/main/java/io/reactivesocket/client/KeepAliveProvider.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProvider.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProviderImpl.java, reactivesocket-core/src/test/java/io/reactivesocket/client/SetupProviderImplTest.java
`SetupProvider` currently does not provide a way to specify data and metadata for the setup frame.
Add a method `setupPayload(Payload)` to support optionally specifying a payload for the setup frame. Default is empty still metadata and data.
Now data or metadata can be specified for a setup from the client.
=> [0.5.x] Setup payload

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProvider.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProviderImpl.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/DisableLeaseSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/LeaseImpl.java, reactivesocket-core/src/main/java/io/reactivesocket/server/ReactiveSocketServer.java, reactivesocket-transport-local/src/main/java/io/reactivesocket/local/internal/PeerConnector.java, reactivesocket-transport-local/src/test/java/io/reactivesocket/ClientDishonorLeaseTest.java, reactivesocket-transport-local/src/test/java/io/reactivesocket/local/LocalSendReceiveTest.java
Today server sends leases even though the client does not honor leases. There are two things here:
- A server should protect itself, even if the client dishonors leases, i.e. leases aren't infinite if the client does not honor. So, the server should still expect requests within capacity from clients and reject all other requests.
- Clients should not receive lease frames as they are not relevant.
`ServerReactiveSocket` to not send leases when the setup is such that client does not honor leases.
Also, added an override in `SetupProvider` to be able to modify the `DisableLeaseSocket` if required.
Expected results and optimizations on the wire w.r.t data transfers.
=> Do not send lease frames for clients that do not honor leases.

reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/ReactiveSocketFrameLogger.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/TcpTransportClient.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/server/TcpTransportServer.java
Tracking ReactiveSocket frames is not easy with wire logging as it logs the bytes written/read.
Added a netty handler to be added as the first handler in the pipeline and logs frame objects as-is written and read on the channel.
Following netty's logging handler design, this handler can be configured to log at a particular log level, which can be changed by the user at runtime.
Better tracking of ReactiveSocket frames on the channel.
=> ReactiveSocket frame logger (tcp)

reactivesocket-core/build.gradle, reactivesocket-examples/build.gradle, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestResponsePerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/AbstractMicrobenchmarkBase.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/BlackholeSubscriber.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/ClientServerHolder.java
No benchmarks for transports.
Added a benchmark to compare request-response across multiple transports. Added local and tcp for now.
Benchmark to give some idea about how different changes impact the perf.
=> Microbenchmarks for tcp and local

reactivesocket-core/src/main/java/io/reactivesocket/ClientReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/DefaultLeaseEnforcingSocket.java
`ClientReactiveSocket` and `ServerReactiveSocket` does not cleanup state (unsubscribe keepalive, leases, etc) when the underlying connection is closed by the peer.
This causes lingering keepAlive and lease writes which keeps failing and emitting errors.
Listen to `DuplexConnection.onClose()` and cleanup when that publisher terminates.
Cleaner shutdown on close of connection.
=> Proper shutdown on underlying connection close.

reactivesocket-core/src/main/java/io/reactivesocket/internal/RemoteReceiver.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/RemoteReceiverTest.java, reactivesocket-publishers/src/main/java/io/reactivesocket/reactivestreams/extensions/internal/ValidatingSubscription.java
`RemoteReceiver` is used for receiving a stream over a `ReactiveSocket`, eg: `requestChannel()` request or `requestStream()` response.
For request stream, it may so happen that the receiver does not subscribe to the request stream. This is OK for `onNext`s but terminal events can flow in without explicit `requestN`s. `RemoteReceiver` does not handle such terminal events today.
Added `missedCompletion` and `missedError` to `RemoteReceiver` that correctly buffers the terminal events if there is no subscription and sends these events if and when a subscriber arrives.
No errors when terminal events flow without subscription.
=> `RemoteReceiver` handle events before subscription.

reactivesocket-core/src/main/java/io/reactivesocket/ClientReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/RemoteReceiver.java, reactivesocket-examples/build.gradle, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/channel/ChannelEchoClient.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/requestresponse/HelloWorldClient.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/stream/StreamingClient.java, reactivesocket-examples/src/main/resources/log4j.properties, reactivesocket-examples/src/test/java/io/reactivesocket/integration/StressTest.java, reactivesocket-publishers/src/main/java/io/reactivesocket/reactivestreams/extensions/internal/processors/ConnectableUnicastProcessor.java
__This contains #185, so do not merge this first, it is just a headsup for review__
In the current implementation stream and channel methods are broken.
Fixed stream and channel methods to work end to end. Also added examples for the same.
They are now implemented using the existing `RemoteReceiver` and `RemoteSender` classes.
One major problem with using `ConnectableUnicastProcessor` was that it does not discriminate between subscriber of request and sender of `requestN` and `cancel` frames. So, if the request source is completed, sending `requestN` and `cancel` frames result in them being rejected by the transport. This is one of the reasons `RemoteReceiver` and `RemoteSender` classes were created.
__request-response implementation is not changed in this change as that needs to be …
=> Fix for `requestChannel` and `requestStream`

reactivesocket-client/src/main/java/io/reactivesocket/client/events/LoadBalancingClientListener.java, reactivesocket-core/src/main/java/io/reactivesocket/events/ClientEventListener.java, reactivesocket-core/src/main/java/io/reactivesocket/events/EventListener.java, reactivesocket-core/src/main/java/io/reactivesocket/events/EventSource.java, reactivesocket-core/src/main/java/io/reactivesocket/events/ServerEventListener.java
__Problem__
Insights into the internals of `ReactiveSocket` is not available for users. eg: Load balancing internals, leases sent/received, keep-alives sent/received, etc.
This change is first of a series of changes intended to address this problem. It only contains the core interfaces to support event publications from `ReactiveSocket` internals.
The model is adopted from the [tried and tested model in `RxNetty`](https://github.com/ReactiveX/RxNetty/issues/98) to provide an event publishing infrastructure that can be used to implement metrics of event firehose. One of the primary guideline of this model is to reduce the object allocations that comes along with an event stream based on emitting an event as an object. Instead, this approach embraces distinct callbacks that …
=> [0.5.x-events] Events interface

reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestResponsePerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/AbstractMicrobenchmarkBase.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/ClientServerHolder.java
Tcp benchmark only utilizes a single eventloop, there is a theory that this could limit througput. Also, how does the behavior change with increasing requests per benchmark is not answered today.
Added two benchmarks:
- A benchmark to utilize more than one TCP connection per benchmark iteration.
- A parameter to run more than one requests per benchmark iteration.
Answer more questions about performance!
Here is the last run:
```
Benchmark                            (requestCount)            (transport)   Mode  Cnt        Score       Error  Units
RequestResponsePerf.requestResponse               1  tcp_multi_connections  thrpt   20    17347.802 ±   322.561  ops/s
RequestResponsePerf.requestResponse               1                    tcp  thrpt   20    16685.702 ±   693.712  ops/s …
```
=> More benchmarks

reactivesocket-core/src/main/java/io/reactivesocket/AbstractReactiveSocket.java, reactivesocket-transport-local/src/main/java/io/reactivesocket/local/LocalServer.java, reactivesocket-transport-local/src/test/java/io/reactivesocket/GracefulShutdownTest.java, reactivesocket-transport-local/src/test/java/io/reactivesocket/test/util/LocalRSRule.java
`AbstractReactiveSocket` does not implement `close()` and `onClose()` correctly. Both of them return `Px.never()`.
This makes it hard for an implementation to do any cleanup actions on close.
Correctly terminate `onClose` `Publisher` after close() is invoked and subscribed.
Also, added test to verify this behavior in the local transport.
Better way to cleanup on close of `AbstractReactiveSocket`.
=> `AbstractReactiveSocket.onClose()` never completes.

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/test/java/io/reactivesocket/ServerReactiveSocketTest.java
`ServerReactiveSocket` upon receiving a `KeepAlive` frame responds with a `KeepAlive` frame as an ack. This ack MUST not have respond flag set to true. Doing so will result in an infinite loop of keep-alive frames sent between the peers.
`ServerReactiveSocket` responds with the respond flag turned off.
No infinite loop of keep-alive frames.
=> Respond to keep-alive with response flag off.

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java
Currently `Frame.toString()` does not print the various flags associated with different frame types. eg: `requestN` value in `RequestN` frame. This limits the usefulness of frame logging.
Added `additionalFlags` string which is generated per frame type.
More insight for frame logging.
=> Additional flags in `Frame.toString()`

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-transport-tcp/build.gradle
[rxnetty rc.5](https://github.com/ReactiveX/RxNetty/releases/tag/v0.5.2-rc.5) has a fix for backpressure which is required for channel/stream implementations.
- Updated tcp transport to `io.reactivex:rxnetty-tcp:0.5.2-rc.5`
- Minor formatting fix for `Frame.toString()`
Latest and greatest dependencies.
=> Update to rxnetty 0.5.2-rc.5

README.md, gradle/buildViaTravis.sh
Currently travis is publishing 0.2.3-SNAPSHOT artifacts for 0.5.x branch.
I am not 100% sure if this is the correct way to make travis publish the correct version, but it is a way!
Modified `buildViaTravis.sh` to override the version, just for snapshot builds.
Correct version number for snapshot.
=> Fix to publish Snapshots to jfrog

reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/AbstractReactiveSocketPerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestResponseLargePayloadPerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestStreamPerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/util/ClientServerHolder.java
Current JMH tests only benchmark smaller payloads "hello". It will be good to know the numbers with larger payloads.
- Refactored `RequestResponsePerf` and extracted a base class that can be used in all benchmarks.
- Added another benchmark class to test different payload sizes.
More insight into perf.
=> JMH test for larger payloads

reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/internal/HdrHistogramGauge.java, reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/internal/HdrHistogramMaxGauge.java, reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/internal/HdrHistogramMinGauge.java, reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/internal/HdrHistogramServoTimer.java, reactivesocket-stats-servo/src/main/java/io/reactivesocket/loadbalancer/servo/internal/SlidingWindowHistogram.java, reactivesocket-stats-servo/src/test/java/io/reactivesocket/loadbalancer/servo/internal/SlidingWindowHistogramTest.java
Problem
Current histogram doesn't resets on every get on every dimension. This creates choppy metrics.
Modifications
Modified the timer to have n histrograms in a queue and rotate of over them to smooth out the histogram over a sliding window. Switched the dimensions of the histrogram to a label called value. Switched the reseting of the histrogram to a closure that is called by the timer instead so it will rotate the histrogram once per window.
Result
Correct metrics over a rolling window.
=> added sliding window histogram

reactivesocket-core/src/main/java/io/reactivesocket/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/RemoteSender.java, reactivesocket-core/src/test/java/io/reactivesocket/ServerReactiveSocketTest.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/RemoteSenderTest.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
`FrameHeaderFlyweight` resolves the frame type as `NEXT_COMPLETE` only if the payload is not empty. Otherwise, the frame is treated as `COMPLETE`.
This is a problem for request-response as this means the response publisher will complete without emitting a response, if the response does not have any data. Such a condition is a failure as request-response should have exaclty one response.
Eliminated the check for data length and always emit `NEXT_COMPLETE` if the complete flag is set.
According to the [protocol](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#response-frame):
```
A Response is generally referred to as a NEXT.
```
So, this behavior would not be a violation of the protocol but will produce empty `onNext` before `onComplete`
Better behavior with empty …
=> Empty Payload Response treated as Complete frame

reactivesocket-core/src/main/java/io/reactivesocket/ClientReactiveSocket.java, reactivesocket-core/src/test/java/io/reactivesocket/ClientReactiveSocketTest.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
__Problem__
Today a client can not retry a request by simply adding a retry operator. eg:
```java
Flowable.fromPublisher(socket.requestResponse(PayloadImpl.EMPTY)).retry()
```
does not work. Instead one has to use
```java
Flowable.fromPublisher(Flowable.defer(() -> socket.requestResponse(PayloadImpl.EMPTY)))
```
The reason is that the implementation creates a `streamId` upon calling `requestResponse` and not on each subscription.
Modify `ClientReactiveSocket` to create a new `streamId` per subscription. This will make sure that each subscription is unique and hence a server will not have an issue accepting such requests.
__Result__
More idiomatic usage of function composition and retry/repeat kind of models.
=> Make `ReactiveSocket` requests lazy

reactivesocket-core/build.gradle
This fixes a cyclic dependency that causes the build to break in Eclipse (with both Gradle plugins).
All tests pass when I run locally, such as:
> ./gradlew :reactivesocket-core:test
> ./gradlew test
So, reactivesocket-core must not actually depend on this ... which would make sense since reactivesocket-test depends on reactivesocket-core, which can't happen.
Despite it building successfully for me locally from command line, I don't know if this has broken something else, so need to see it go through the Travis CI build/test cycle.
=> Remove Cyclic Dependency

reactivesocket-core/src/main/java/io/reactivesocket/ClientReactiveSocket.java
Seems like a typo
Two constructors are
```
public RemoteSender(Publisher<Frame> originalSource, Runnable cleanup, int streamId,  int initialRemoteRequested) {    
public RemoteSender(Publisher<Frame> originalSource, Runnable cleanup, int streamId) {
```
=> Correct call to RemoteSender - streamId and initialRemoteRequested

reactivesocket-core/src/main/java/io/reactivesocket/util/PayloadImpl.java, reactivesocket-core/src/test/java/io/reactivesocket/util/PayloadImplTest.java
__Problem__
`PayloadImpl` caches `data` and `metadata` buffers. This means once those buffers are read, they can not be reused as the pointer of `ByteBuffer` has moved to the end of buffer.
This restricts the usage of `PayloadImpl` instance with something like:
```java
socket.requestResponse(new PayloadImpl("Hello")).retry(2);
```
For any retry in the above code, data read from the payload instance will be empty.
- store buffer `position()` on creation and reset them on every `get()`.
- Additional constructor to override this behavior and create a payload for single use.
- `PayloadImpl` defaults to reusable payload.
__Result__
Possible to retry a request without having a custom `Payload` implementation.
=> Reusable `Payload`

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancerInitializer.java, reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancerSocketMetrics.java, reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancingClient.java, reactivesocket-client/src/main/java/io/reactivesocket/client/events/LoadBalancingClientListener.java, reactivesocket-client/src/main/java/io/reactivesocket/client/events/LoggingLoadBalancingClientListener.java
__Problem__
No events are published for `LoadBalancer`
Publishing events for `LoadBalancer`
__Result__
More events, more insight!
=> Event publishing for `LoadBalancer`

reactivesocket-core/src/main/java/io/reactivesocket/events/EventListener.java
We haven't yet killed off requestSubscription and the Frame type constants still include it, so I'd expect this to work for now.
=> fails on requestSubscription calls

reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/ClientEventListenerImpl.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/EventListenerImpl.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/LoadBalancingClientListenerImpl.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/internal/ErrorStats.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/internal/LeaseStats.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/internal/RequestStats.java, reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/internal/SpectatorUtil.java
__Problem__
Currently we have custom implementation of timers and counters.
These implementations are somewhat not recognized inside Netflix and hence does not get published to our metrics system.
At this point it is better to use the native counterparts than to debug the issue, we can revert to the custom implementation when we see performance issues.
Replace custom usages with native spectator classes.
__Result__
Metrics correctly published.
=> Using native spectator counter and timer

reactivesocket-spectator/src/main/java/io/reactivesocket/spectator/ServerEventListenerImpl.java
__Problem__
Missed in #228
Remove the remaining `ThreadLocalAdderCounter`
__Result__
Metrics correctly published.
=> Missed moving to native spectator counter.

reactivesocket-core/src/main/java/io/reactivesocket/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/RequestFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/SetupFrameFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/FrameHeaderFlyweightTest.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/SetupFrameFlyweightTest.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/ReactiveSocketLengthCodec.java
Makes frame and metadata length 24 bits.
Metadata length also excludes the length field itself
Moves streamId to front
Makes frame type 6 bits and flags 10 bits
Make all used flag 10 bits
Some new unit tests to verify all this.
=> Update frame header to 1.0 spec

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/SetupFrameFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/SetupFrameFlyweightTest.java
Properly parse SETUP frames with resumption but no support internally besides that.
=> Properly handle SETUP frames with RESUME_ENABLED

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/KeepaliveFrameFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/KeepaliveFrameFlyweightTest.java
Adds a 64 bit (always zero) last position to the KEEPALIVE. It's also skipped when reading. Simple unit test to verify we can still read data.
=> Add last position to KEEPALIVE frame

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/VersionFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/VersionFlyweightTest.java
`Frame[0] => Stream ID: 0 Type: SETUP Version: 65536 keep-alive interval: 2147483647 max lifetime: 2147483645 metadata mime type: application/x.reactivesocket.meta+cbor data mime type: application/binary Payload:`
after
`Frame[0] => Stream ID: 0 Type: SETUP Version: 1.0 keep-alive interval: 2147483647 max lifetime: 2147483645 metadata mime type: application/x.reactivesocket.meta+cbor data mime type: application/binary Payload:`
=> version pretty print

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/ClientReactiveSocketTest.java, reactivesocket-core/src/test/java/io/reactivesocket/FrameTest.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/FrameHeaderFlyweightTest.java, reactivesocket-examples/src/test/java/io/reactivesocket/integration/IntegrationTest2.java
The existing COMPLETE frame now generates a real PAYLOAD frame with the NEXT bit unset but the COMPLETE bit set. NEXT_COMPLETE sets both while NEXT only sets the NEXT bit.
Added tests to verify this behavior and also used reactivesocket-cli to verify frames sent/received.
Currently throwing an exception if we see a PAYLOAD frame with neither NEXT nor COMPLETE set pending https://github.com/ReactiveSocket/reactivesocket/issues/226.
=> Implement Payload NEXT bit

reactivesocket-core/src/jmh/java/io/reactivesocket/ReactiveSocketPerf.java, reactivesocket-core/src/main/java/io/reactivesocket/ClientReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/LimitableRequestPublisher.java, reactivesocket-core/src/test/java/io/reactivesocket/FrameTest.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestResponsePerf.java, reactivesocket-examples/src/jmh/java/io/reactivesocket/perf/RequestStreamPerf.java, reactivesocket-test/src/main/java/io/reactivesocket/test/ClientSetupRule.java, reactivesocket-test/src/main/java/io/reactivesocket/test/TestReactiveSocket.java, reactivesocket-transport-netty/src/test/java/io/reactivesocket/transport/netty/TcpClientServerTest.java
Problem
client wasn't sending correct initial request n (#264)
Modification
In LimitableRequestPublisher the added a call to request n after subscription, and in the ClientReactiveSocket moved sending the frames into a doOnRequest() method so that it can get the initial request n. 
Result
client sends initial request n
=> fixes client stream request n

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProvider.java, reactivesocket-core/src/main/java/io/reactivesocket/client/SetupProviderImpl.java, reactivesocket-core/src/main/java/io/reactivesocket/server/DefaultReactiveSocketServer.java, reactivesocket-core/src/main/java/io/reactivesocket/server/ReactiveSocketServer.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
This change just make it possible for client and server implementors to provide an alternative errorConsumer
=> Allow errorConsumer to be set

rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaClientDriver.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaTCPClient.java
Modified the javaClientDriver to open a single TCP connection, instead of opening a new TCP connection for every new request/stream.
=> Single TCP connection for TCK driver client

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/duplex/DuplexClient.java
Currently, it is not possible for the client side acceptor to call the
server rsocket.
This change exposes the server rsocket to the client acceptor.
=> Exposed server rsocket to client acceptor

rsocket-core/src/test/java/io/rsocket/RSocketFactoryTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/BaseClientServerTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SecureWebsocketClientServerTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SecureWebsocketClientSetupRule.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpClientServerTest.java
Secure websocket test (failing)
```
22:15:46,145 ERROR [reactor-http-nio-1] (Loggers.java) - Handler failure while no child channelOperation was present
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a757067726164653a20776562736f636b65740d0a636f6e6e656374696f6e3a20757067726164650d0a7365632d776562736f636b65742d6b65793a20617068514e3979663979514e63424f4b7331537964513d3d0d0a686f73743a206c6f63616c686f73743a35343237390d0a7365632d776562736f636b65742d6f726967696e3a20687474703a2f2f6c6f63616c686f73743a35343237390d0a7365632d776562736f636b65742d76657273696f6e3a2031330d0a757365722d6167656e743a2052656163746f724e657474792f302e362e332e52454c454153450d0a6163636570743a202a2f2a0d0a0d0a
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1060)
at …
```
=> Refactor transport specific tests 

rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SecureWebsocketClientServerTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SecureWebsocketClientSetupRule.java
For secure websocket, the path param in the HttpClient.ws call must be a complete URL instead of just the path.
=> working wss

rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpUriHandler.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketUriHandler.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/NettyUriTransportRegistryTest.java
a url like "/echo" would cause a NPE as scheme is null
=> don't NPE on bad urls

rsocket-core/src/main/java/io/rsocket/util/CloseableAdapter.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
Given an existing project using reactor-netty, what does the API for creating a websocket server on a particular path look like e.g. "/ws".  This helps with serving same domain HTML content that uses the websocket.
=> Support websocket as part of a larger server

rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaClientDriver.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/TckIndividualTest.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/main/Main.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/server/JavaServerDriver.java, rsocket-tck-drivers/src/test/java/io/rsocket/tckdrivers/TckTest.java
rsocket-cpp requires this to run cross implementation compatibility tests 
Removing this file did not break anything because Cross implementation compatibility tests were using an older version of rsocket-java
Following changes are temporary
RSocket client = createClient(this.uri);
this.createClient = () -> client;
This part will be rewritten when I will add the support for multiple clients. Each test will be run by a new client object(s).
=> Added the tck-main file 

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java, rsocket-test/src/main/java/io/rsocket/test/ClientSetupRule.java
Removes the need for casting when server transport returns a subtype of Closeable, e.g. NettyContextCloseable.
=> Fix types in RSocketFactory

rsocket-core/src/main/java/io/rsocket/util/CloseableAdapter.java
Method 'onClose()' recurses infinitely, and can only end by throwing an exception
=> Infinite recursion

rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.java
Type parameters being named identically to visible types in the current scope
=> Type parameter 'T' hides type parameter 'T'

rsocket-core/src/main/java/io/rsocket/frame/FrameHeaderFlyweight.java
Condition 'metadata != null' is always 'true' when reached
=> redundant condition

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java
There was a race condition in the RSocketServer where the connection was receiving data before the sendProcessor was created. This was leading to a null point exception. I moved the order so that the sendProcessor is constructed and subscribed too before receiving incoming frames.
=> null pointer caused by race condition

rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/reactivestreams/AeronClientChannelConnector.java
'ConcurrentHashMap<AeronSocketAddress, Subscription>' may not contain objects of type 'Long'
=> fix client unsubscribe

rsocket-core/src/jmh/java/io/rsocket/RSocketPerf.java, rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java
replace lambdas with method references
replace statement lambda with expression lambda
redundant local variable
Unchecked assignment: 'org.reactivestreams.Subscriber' to 'org.reactivestreams.Subscriber<? super io.rsocket.Payload>'
Unchecked assignment: 'org.reactivestreams.Subscriber' to 'org.reactivestreams.Subscriber<? super java.lang.Void>'
riber' to 'org.reactivestreams.Subscriber<? super java.lang.Void>'
The declared exception 'Exception' is never thrown
=> fix compiler flow issues

rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/NettyDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
Switching NettyDuplexConnection to use a MonoProcessor so that onClose isn't tied directly to Netty.
=> use MonoProcessor to close and not depend on netty

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/SwitchTransform.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java
RSocket server was being closed when it receives an exception that isn't being handle. It should call the error consumer, and continue processing requests.
=> Server Connection Closing on Exception

rsocket-core/src/main/java/io/rsocket/AbstractRSocket.java, rsocket-core/src/main/java/io/rsocket/Closeable.java, rsocket-core/src/main/java/io/rsocket/frame/FrameHeaderFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/KeepaliveFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/SetupFrameFlyweight.java
This commit improves a few pieces of javadoc, notably documenting most FLAG constants and marking STRICT as deprecated (as it has been removed from the protocol after v0.2).
=> Add documentation to flag constants, mark STRICT as deprecated

rsocket-examples/build.gradle, rsocket-examples/src/main/resources/log4j.properties
Now there is logging outupt. I've also tweaked the logging settings to
start at DEBUG and to show the class name at least.
=> Add log4j dependnecy to examples project

build.gradle, gradle.properties, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/util/NonBlockingHashMap.java, rsocket-test/build.gradle, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/NettyDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java
Merge some changes from JCTools, clean up a few places where synchronization is no longer needed after switching to NonBlockingHashMapLong
=> Update dependencies, cleanup RSocketClient/Server implementation

build.gradle, rsocket-core/src/jmh/java/io/rsocket/RSocketPerf.java, rsocket-core/src/jmh/java/io/rsocket/perfutil/TestDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/Closeable.java, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/frame/FrameHeaderFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/SetupFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/util/ConcurrentAutoTable.java, rsocket-core/src/main/java/io/rsocket/util/NonBlockingHashMap.java, rsocket-core/src/main/java/io/rsocket/util/NonBlockingHashMapLong.java, rsocket-core/src/main/java/io/rsocket/util/UnsafeAccess.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/reactivestreams/AeronChannelServer.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java
Most of the diff here is from running googleJavaFormat -- the real changes are in RSocketClient/Server.
=> Simplify RSocketClient/Server implementation and avoid unnecessary flatMap

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
=> Release SetupFrame on RSocket version mismatch

build.gradle, rsocket-core/build.gradle, rsocket-examples/build.gradle, rsocket-load-balancer/build.gradle, rsocket-spectator/build.gradle, rsocket-test/build.gradle, rsocket-transport-aeron/build.gradle, rsocket-transport-local/build.gradle, rsocket-transport-netty/build.gradle
In order to publish to Maven Central, POMs must contain a minimum set of elements.  The automatically generated POM from Gradle's `maven-publish` plugin does not contain these elements.  This change adds build functionality to ensure that the generated POMs are Maven Central compatible.
=> Maven Central POM Requirements

build.gradle, rsocket-core/build.gradle, rsocket-examples/build.gradle, rsocket-load-balancer/build.gradle, rsocket-test/build.gradle, rsocket-transport-aeron/build.gradle, rsocket-transport-local/build.gradle, rsocket-transport-netty/build.gradle
This change introduces JUnit 5 to the build.  It enables JUnit 5 support in Gradle and adds the required dependencies to write JUnit 5 types.  The change does not remove the JUnit 4 dependencies yet, as the tests have not been converted.
=> Introduce JUnit 5

.travis.yml
This change disables the Java 9 build because in some circumstances the Javadocs for the Aeron transport are failing.  This change should be reverted once this has been sorted out in that code.
=> Disable Java 9 Build

rsocket-core/src/main/java/io/rsocket/fragmentation/FrameFragmenter.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java, rsocket-core/src/main/java/io/rsocket/framing/AbstractRecyclableFrame.java, rsocket-core/src/main/java/io/rsocket/framing/DataFrame.java, rsocket-core/src/main/java/io/rsocket/framing/ErrorFrame.java, rsocket-core/src/main/java/io/rsocket/framing/ExtensionFrame.java, rsocket-core/src/main/java/io/rsocket/framing/MetadataFrame.java, rsocket-core/src/main/java/io/rsocket/framing/MetadataPushFrame.java, rsocket-core/src/main/java/io/rsocket/framing/PayloadFrame.java, rsocket-core/src/main/java/io/rsocket/framing/RequestChannelFrame.java, rsocket-core/src/main/java/io/rsocket/framing/RequestFireAndForgetFrame.java, rsocket-core/src/main/java/io/rsocket/framing/RequestResponseFrame.java, rsocket-core/src/main/java/io/rsocket/framing/RequestStreamFrame.java, rsocket-core/src/main/java/io/rsocket/framing/ResumeFrame.java, rsocket-core/src/main/java/io/rsocket/framing/SetupFrame.java, rsocket-core/src/main/java/io/rsocket/util/AbstractionLeakingFrameUtils.java, rsocket-core/src/main/java/io/rsocket/util/DisposableUtils.java
Previously, there were a couple of frames that converted `String`s to `ByteBuf`s automatically as part of construction.  Those frames though, retained any `ByteBuf`s passed into them so that they could be released by the creators as necessary.  Since the automatic construction was not doing this release on the `String`-based `ByteBuf`s, there was a minor leak of references.  This change updates those locations to release the `String`-based `ByteBuf`s and accurately account for their retention and release.
=> Fix Reference Count Leak

build.gradle, gradle.properties
Previously the project version in the build was explicitly specified within the build script itself.  This way of specifying the project version makes the value non-overrideable from the command line.  This change moves that value to the `gradle.properties` file where it becomes a "normal" property, overridable using the standard `-P` syntax.
=> Extract Project Version

bintray.gradle, build.gradle
Previously, an update to the build system took a stab at uploading releases to Bintray and them promoting them to Maven Central.  Unsurprisingly, without a release to test against, this didn't work on the first try.  The first change required a move of the bintray configuration from the top-level project to each subproject that would be published.  Unlike before, this is now a subset of projects excluding things like the integration tests.  Second, this change finishes improvements to the Maven POM in order to meet the Maven Central requirements for publication.  Specifically three developers were added to the POMs in order for Sonatype to reach them if necessary.
=> Upload to Bintray and Maven Central

README.md, artifactory.gradle, rsocket-core/build.gradle, rsocket-core/src/test/java/io/rsocket/util/DefaultPayloadTest.java, rsocket-examples/build.gradle, rsocket-load-balancer/build.gradle, rsocket-micrometer/build.gradle, rsocket-transport-aeron/build.gradle, rsocket-transport-local/build.gradle, rsocket-transport-netty/build.gradle
Previously, an update the build system resulted in the Maven dependencies being aggressively calculated, before each project add dependencies to itself. This change updates the ordering of this calculation such that it happens after each project configures itself.  In addition, this change goes through each project and ensures that the dependencies are scoped appropriately in order to achieve the a minimal and accurate Maven POM.
[Sample of the generated POMs](https://gist.github.com/nebhale/668720e6fff89df77424f03d731a79bc)
=> Maven Dependency Improvements

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FrameFragmenter.java, rsocket-core/src/main/java/io/rsocket/util/NumberUtils.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FrameFragmenterTest.java, rsocket-core/src/test/java/io/rsocket/util/NumberUtilsTest.java
Previously, if a user configured a non-positive (<=0) MTU for fragmentation, both fragmentation and reassembly were disabled.  Given that a receiver must always be prepared to reassemble fragmented frames (there is no handshake or flag that both parties must agree to) requiring fragmentation to enable reassembly was to strict.  This change updates the fragmenter to handle an MTU of size 0 as an indicator that there should be no fragmentation, but still enable reassembly.  The RSocketFactory was also updated to ensure that the fragmenter is always added, rather than skipping it when the MTU was zero.
=> Always Reassemble Regardless of MTU

rsocket-test/src/main/java/io/rsocket/test/SlowTest.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
Currently the `TransportTest#requestChannel2_000_000` test (for all transports) takes a very long time on some systems.  It's a useful test to have, but not necessarily to run at all times.  This change creates an `@SlowTest` annotation that is meta-annotated so that tests will only be enabled if `TEST_SLOW_ENABLED=true` has been set.
[resolves #511 ]
=> Slow Test Run Configuration

rsocket-core/src/main/java/io/rsocket/RSocketServer.java
=> Fixed sending complete signal for mono.empty()

rsocket-core/src/main/java/io/rsocket/Frame.java
Currently there are times when  Frames are being released and the content field is null. This checks to see if the content is null and prevents a NullPointerException from being thrown.
=> check for nulls in Frame

build.gradle, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/KeepAliveHandler.java, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/util/ByteBufPayload.java, rsocket-core/src/main/java/io/rsocket/util/DefaultPayload.java, rsocket-core/src/test/java/io/rsocket/KeepAliveTest.java, rsocket-examples/src/test/java/io/rsocket/integration/InteractionsLoadTest.java
=> Reimplementation of keep-alives according to spec

build.gradle, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-examples/src/test/java/io/rsocket/integration/InteractionsLoadTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpUriHandler.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/CloseableChannel.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketSecureTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/TcpClientTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/WebsocketClientTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/CloseableChannelTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/TcpServerTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketRouteTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java
=> Upgrade reactor to Californium-RELEASE

build.gradle, gradle.properties
Provide dependency onto the reactor's snapshots in case of a BUILD-SNAPSHOT version of the artifact
=> update version and provide dependency on to Reactor Snapshot

rsocket-core/src/main/java/io/rsocket/internal/SwitchTransformFlux.java, rsocket-core/src/test/java/io/rsocket/internal/SwitchTransformFluxTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpUriHandler.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/CloseableChannel.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketSecureTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/CloseableChannelTest.java
Relates to https://github.com/reactor/reactor-netty/issues/460. Also applied formatter as separate commit
=> Workaround reactor-netty issues in setup rejection verification code

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTerminationTest.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java
Fixes #468 , likely relates to #540
=> Fix current and future streams not terminating after connection dispose

rsocket-core/src/jmh/java/io/rsocket/framing/FrameTypePerf.java, rsocket-core/src/main/java/io/rsocket/framing/FrameType.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java
Switching FrameType flag back to bits. Current version uses an EnumSet which requires a contains method call. This method traverses and array, which requires you do this every time you created a Frame. This one does a bitmask and equals.
=> Switching FrameType flags back to bits

build.gradle, gradle.properties, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/SendPublisher.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
SendPublisher can use the queue from the UnboadedProcessor now
Removed dependency on JCTools
Use MonoProcessor for request/reply instead of UnicastProcessor
=> More performance improvements

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java
I encountered a null pointer exception inside RSocketClient::cleanUpSubscriber because subscriber was null. The only way this could happen is if the receivers map is modified while it is being iterated over. The solution is to use the forEach method instead of iterator, which is properly synchronized.
=> Replace for loops with forEach in RSocketClient/Server to fix non-deterministic behavior

rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java
https://github.com/rsocket/rsocket-java/pull/467/files#diff-e9943f246be37dc1abf9a2821d305580R103
This change seems to be invalid and should be reverted
=> Restore logging message. Fixes #559.

README.md
Signed-off-by: pawel.piotr.mackowski@gmail.com
=> readme zero copy section, should be reduce latency

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java
This PR fixes #592 for 1.0.x brunch
=> fixes issue with requestChannel never completes if server cancels (#592)

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-core/src/test/java/io/rsocket/RSocketServerTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java
This PR provide a partial fix for #514 and reintroduce usage of `LimitableRequestPublisher` as of its initial design.
At a moment all connected `LimitableRequestPublisher` receives the same request size as from the connection. It means that upstream still an overflow UnboundProcessor but with less probability (it can happen in case we have super many requestChannel/requestStream connections which infinitely send data)
In the future PRs we have to revise the implementation of UnboundedProcessor in order to have proper guarantees on overflow prevention.
=> fixes uncontrolled data sending in case of direct propagation of request from requester

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-core/src/test/java/io/rsocket/RSocketServerTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java
=> fixes uncontrolled data sending in case of direct propagation of request from requester (#595)

build.gradle, rsocket-core/jmh.gradle, rsocket-core/src/jmh/java/io/rsocket/MaxPerfSubscriber.java, rsocket-core/src/jmh/java/io/rsocket/PerfSubscriber.java, rsocket-core/src/jmh/java/io/rsocket/RSocketPerf.java, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java, rsocket-core/src/test/java/io/rsocket/internal/LimitableRequestPublisherTest.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/channel/ChannelEchoClient.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java
1) Reduce the number of used Atomics within the code base. As you can see in PR, there were a few places with applied `first` elements strategy. In all of those cases, usage of atomic was redundant since Reactive-Streams spec and Reactors implementation guarantees happens-before and [serialized](https://github.com/reactive-streams/reactive-streams-java#term_serially) access to the object (Subscriber / Subscription) so having an additional object with volatile access is redundant and give more overhead
2) Reduce the number of allocated objects. In many cases, we use too many Reactors operators where actual logic can be implemented within one `BaseSubscriber`. Thus, this PR eliminates redundant transformations and minimize function flow. Also, dynamic invocations give its overhead, so there …
=> General performance improvements

gradle.properties, rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketTransportIntegrationTest.java
This PR provides access to `ServerTransport.ConnectionAcceptor` which
simplifies integration with existing `HttpServer` and does not mandate
to start HttpServer with RSocketServer. In addition,
`WebSocketRouteTransport` exposes api which shares common functionality
for WS BiFunction setup
=> exposes access to connection acceptor

build.gradle, rsocket-core/src/main/java/io/rsocket/frame/FrameUtil.java, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/WebsocketClientTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketRouteTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java, rsocket-transport-netty/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This PR provides a WebSocket transport's frame size setup with regards
of current RSocket fragment size.
=> fixes bug with incorrect WS framesize setup.

rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java, rsocket-core/src/main/java/io/rsocket/frame/decoder/DefaultPayloadDecoder.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java, rsocket-transport-netty/src/test/resources/logback-test.xml
=> fixes issue with fragmentation when the MTU size is set to 64 bytes

rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-load-balancer/src/test/java/io/rsocket/client/LoadBalancedRSocketMonoTest.java
Fixes #622 
Also cleaned up a few things in the test that weren't being used.
=> Refresh sockets on `select` in LoadBalancedRSocketMono before checking for active sockets

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/ClientSetup.java, rsocket-core/src/main/java/io/rsocket/internal/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveFramesAcceptor.java, rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveHandler.java, rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveSupport.java, rsocket-core/src/main/java/io/rsocket/resume/InMemoryResumableFramesStore.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/KeepAliveTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/SendPublisher.java
Use `Flux.generate` for resume stream of in-memory store.
Add `KeepAliveHandler` tests for resumable case.
Replace bugfix in https://github.com/rsocket/rsocket-java/pull/618 as It caused frames leak on resumption
=> Resume cleanup round

.travis.yml, artifactory.gradle, bintray.gradle
To know if the project builds well with newer Java versions. Publishing to artifactory/bintray has been disabled for Java != 8.
Fixes #588.
=> [#588] Add OpenJDK 11 and 12 build on Travis

rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/ServerRSocketSession.java
The single arg form with a Throwable is a pre formatted message in slf4j
```
21:19:34.781	Starting session timeout due to error: {}
java.nio.channels.ClosedChannelException
at io.rsocket.resume.ResumableDuplexConnection.disconnect(ResumableDuplexConnection.java:326)
```
=> Fix logging formatting

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/plugins/PluginRegistry.java, rsocket-core/src/test/java/io/rsocket/KeepAliveTest.java, rsocket-core/src/test/java/io/rsocket/RSocketRequesterTerminationTest.java, rsocket-core/src/test/java/io/rsocket/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/SetupRejectionTest.java
`RSocketClient` and `RSocketServer` names for requester and responder are misleading because each side of connection has both, and they can be confused with client and server of `RSocketFactory`. Happened more than once already so It makes sense to rename them appropriately https://github.com/rsocket/rsocket-java/issues/640#issuecomment-494313461.
=> Rename internal components to match their purpose

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/test/java/io/rsocket/KeepAliveTest.java, rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java
to either requester or responder, regardless of connection side. This would simplify lease by removing coupling between requester and responder. Also fixes MetadaPush related issue https://github.com/rsocket/rsocket-java/issues/470
=> ClientServerMultiplexer should properly route zero non-setup frames

rsocket-core/src/main/java/io/rsocket/metadata/CompositeMetadataFlyweight.java, rsocket-core/src/test/java/io/rsocket/metadata/CompositeMetadataFlyweightTest.java
This fixes potential false positives in the encodeMetadataHeader
method "ASCII only" check that results in IllegalArgumentException.
The first byte is readable but not actually written when performing
the check, yet we would consider it in `isText` (looking at a random
byte value).
=> Fix CompositeMetadataFlyweight check of ASCII only custom mime

rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-load-balancer/src/main/java/io/rsocket/client/RSocketSupplierPool.java
Mainly fix [issue](https://github.com/rsocket/rsocket-java/issues/652)
fix: LoadBalancedRSocketMono#activeSockets and RSocketSupplierPool#leasedSuppliers are not in sync
add: more logs to help debugging
fix: log when factoryPool has new items
=> fix: LoadBalancedRSocketMono and RSocketSupplierPool not in sync

rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketClient.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketClientHandler.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java, rsocket-transport-netty/src/test/resources/logback-test.xml
Currently if the WebSocket transport receives a frame a Ping,Pong or Close frame it doesn't handle it properly. It passes it on to RSocket which creates an exception. I added logic to handle the ping and pong frames. I also added logic to handle a close frame.
=> added logic to handle different websocket frames

rsocket-core/src/jmh/java/io/rsocket/StreamIdSupplierPerf.java, rsocket-core/src/main/java/io/rsocket/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/StreamIdSupplier.java, rsocket-core/src/test/java/io/rsocket/StreamIdSupplierTest.java
wraps the stream id when it reaches 2^31 - it also checks for active streams and increments the id if it finds a collision
=> stream id wrap fix

rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java, rsocket-core/src/test/java/io/rsocket/buffer/Tuple3ByteBufTest.java
Fix for this issue: https://github.com/rsocket/rsocket-java/issues/663
=> fixes array copy in Tuple3ByteBuf

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/SocketAcceptor.java, rsocket-core/src/main/java/io/rsocket/plugins/PluginRegistry.java, rsocket-core/src/main/java/io/rsocket/plugins/SocketAcceptorInterceptor.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java
Currently an `RSocketInterceptor` can only intercept requests, but has no visibility into connection setup like metadata  and data mime types, see https://github.com/rsocket/rsocket-java/issues/661#issuecomment-512067225. Especially on the server side there is no way for an interceptor to access this information which can be critical (e.g. for a security interceptor).
This pull request adds `SocketAcceptorInterceptor` and also updates support for `SocketAcceptor` so both are supported symmetrically.
=> Add SocketAcceptorInterceptor

rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java, rsocket-core/src/test/java/io/rsocket/internal/UnicastMonoProcessorTest.java
This PR includes (and will include - work in progress) various performance tunning and optimizations
=> Performance Optimization Session

build.gradle, gradle/artifactory.gradle, gradle/publications.gradle
Prior to this change, the Gradle publication configuration would be
applied to the wrong level of projects (subprojects of subprojects!),
resulting in no artifacts being published to the repository.
This commit updates the JFrog artifactory Gradle plugin version and
fixes the application of the publication configuration to align with
what's been done with artifactory and bintray configurations.
Signed-off-by: Brian Clozel <bclozel@pivotal.io>
=> Fix Gradle publication configuration

build.gradle
Prior to this change, the default groupId "rsocket-java" would be used
for all RSocket artifacts. This commit fixes the group name to
"io.rsocket" for all Gradle subprojects.
This change is reflected in the published POMs and BOM.
=> Fix artifacts groupId

rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java
If servers are intentionally rejecting connections, refreshSockets-after-closing-socket on client side may cause infinite loop of opening and closing (immediately reset on server side) connections.
=> do not refreshSockets after closing socket

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
I just discovered the BiConsumer vs the SocketAcceptor variants confuse
the compiler with lambda syntax. The deprecation shouldn't be necessary
anymore.
=> Remove deprecated method in ClientRSocketFactory

rsocket-bom/build.gradle
=> Remove rsocket-examples from generated BOM.

rsocket-core/src/main/java/io/rsocket/frame/decoder/DefaultPayloadDecoder.java
This PR fixes https://github.com/rsocket/rsocket-java/pull/616#pullrequestreview-324559437
=> remove unnecessary synchronized from default decoder

rsocket-core/src/main/java/io/rsocket/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/exceptions/CustomRSocketException.java, rsocket-core/src/main/java/io/rsocket/exceptions/Exceptions.java, rsocket-core/src/main/java/io/rsocket/frame/ErrorFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/ErrorType.java, rsocket-core/src/test/java/io/rsocket/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/SetupRejectionTest.java, rsocket-core/src/test/java/io/rsocket/exceptions/ExceptionsTest.java, rsocket-core/src/test/java/io/rsocket/exceptions/TestRSocketException.java
This PR extends the current implementation of error handling to match what is defined in the spec and let the user use a range of user allowed error codes using `CastomRSocketException` class
=> fixes error handling to match specification

build.gradle
This PR disabled Gradle 6 modules feature.
As I figured out bintray-gradle-plugin does not have proper integration with that future (hence `.module` files are not published along with other artifacts) so the simples solution, for now, is to disable that feature
Fix for #746 
=> disables gradle modules feature

.travis.yml, gradle/wrapper/gradle-wrapper.properties
This PR:
1. upgrades Gradle to 6.3 which support JDK14 
2. changes Travis build matrix and replaces JDK 13 build to JDK 14 build
=> provides support for the JDK 14 based builds

rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/DefaultClientRSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/DefaultConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/core/DefaultServerRSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java, rsocket-core/src/main/java/io/rsocket/core/StreamIdSupplier.java, rsocket-core/src/main/java/io/rsocket/core/package-info.java, rsocket-core/src/main/java/io/rsocket/plugins/SocketAcceptorInterceptor.java, rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java, rsocket-core/src/test/java/io/rsocket/core/ConnectionSetupPayloadTest.java, rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTerminationTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java, rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java, rsocket-core/src/test/java/io/rsocket/core/StreamIdSupplierTest.java, rsocket-core/src/test/java/io/rsocket/core/TestingStuff.java
The top-level `io.rsocket` package is at the center of a large package cycle because it contains both high level abstractions, accessed by everything, and also core protocol implementations classes that access everything:
This change extracts interfaces for `ClientRSocketFactory`, `ServerRSocketFactory`, and `ConnectionSetupPayload`, and moves the core implementations into a sub-package without references to it from the top-level package. After the changes:
This isn't the end of it but it helps quite a bit while keeping the refactoring functionally neutral and backwards compatible.
=> Reduce top-level package dependencies

rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/core/DefaultConnectionSetupPayload.java
Follow-up fix for 0ac54d4b. 
Changing `ConnectionSetupPayload` from abstract class to interface is problematic when framework code compiled against newer RSocket is used in an application on existing version. It is now restored as an abstract class. `DefaultConnectionSetupPayload` however remains in the "core" sub-package to avoid the package cycle with "frame".
=> Restore ConnectionSetupPayload as abstract class

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
Allow `RSocketFactory` to be created with a pre-created instance of `RSocketConnector` or `RSocketServer`. This helps higher level frameworks to support both old and current APIs.
=> RSocketFactory wrapping constructors

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
Removed frames should not be sent to the remote side upon receiving some specific signals, thus were removed accordingly without braking logical functionality
=> Removes redundant frames being sent

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
This PR fixes a bug on the requester side and ensures that the requester is capable of handling requests when its publisher has already sent or received completion.
The Bug here is in the fact that RequestChannel on the requester side has 2 maps to track the state:
- `receivers` which is there to receive OnNext/OnError/OnComplete signals 
- `senders` -  requestChannel specific map to hold a subscription and receive the request/cancel signals from the remote.
This means if one is absent and another is present - the stream is in the half-closed state.
Originally, we had that -> https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java#L562
```
Subscriber<Payload> receiver = receivers.get(streamId);
if (receiver == null) { …
```
=> fixes requestChannel and ensure support of half-closed state

rsocket-core/src/main/java/io/rsocket/Closeable.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java
This PR is a followup to previous `RSocketFactory#errorConsumer` deprecation and future removal. 
That said, we have to have access to the reason of RSocket termination and right now it would be the best to enhance `Mono<Void> onClose` and propagate the root-cause error (e.g Stream ID 0 errors which are terminal) over that API
=> Send root-cause errors from connection to onClose of RSocket

rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java
This PR provides alignment for UnboundedProcessor with Reactor UnicastProcessor to avoid leaking.
Also, this PR provides extra `isDisposed` check in ResumableDuplexConnection to reduce number of leaks caused because of racing
=> Fixes possible elements' leaks occurrence

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
`RSocketConnector` and `RSocketServer` now default to a no-op errorConsumer since that's deprecated with no replacement. `RSocketFactory` retains its current default of printing the stacktrace.
=> Default errorConsumer to no-op in the new API

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/frame/DataAndMetadataFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/LeaseFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/MetadataPushFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/PayloadFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/RequestChannelFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/RequestFireAndForgetFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/RequestResponseFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/RequestStreamFrameFlyweight.java, rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java, rsocket-core/src/test/java/io/rsocket/buffer/LeaksTrackingByteBufAllocator.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/frame/ByteBufRepresentation.java
This PR provides 4 central things:
1. Ensures if there goes something during `Payload` to the frame we will not get any memory leaks in the end (first commit in the list)
2. Fixes `onDiscard` leak which did not work correctly because `actual` subscriber was nulled to early
3. Ensures that we will not have the wrong frame order in case of racing the first `Payload` sending and cancel. Also, it moves `onDiscard` hook to the very bottom in case of `requestChannel` to ensure the first payload is not leaked 
4. Enables a set of tests that ensures that #757 and #733 are fully or partially fixed.
=> provides more `ByteBuf` leaks fixes

rsocket-core/src/main/java/io/rsocket/AbstractRSocket.java, rsocket-core/src/main/java/io/rsocket/RSocket.java, rsocket-core/src/main/java/io/rsocket/SocketAcceptor.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/channel/ChannelEchoClient.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/duplex/DuplexClient.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/requestresponse/HelloWorldClient.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/StreamingClient.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-examples/src/test/java/io/rsocket/integration/InteractionsLoadTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java, rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java, rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-test/src/main/java/io/rsocket/test/PingHandler.java, rsocket-test/src/main/java/io/rsocket/test/TestRSocket.java, rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketTransportIntegrationTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPingPongIntegrationTest.java
This change deprecates `AbstractRSocket` in favor of implementing `RSocket` directly. In turn RSocket has default methods for the basic interactions while `onClose()` now returns `Mono.never()` by default and has to be implemented anyway if it is to do something more meaningful.
In addition `SocketAcceptor` provides static factory methods as shortcuts for handling one type of interaction with a lambda syntax.
=> Deprecate AbstractRSocket and provide alternative

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
The mentioned NPE case may happen rarely due to racing, thus not always can be reproduced in racing tests (or can be reproduced rarely)
Just observed that case in https://travis-ci.org/github/rsocket/rsocket-java/jobs/681587006
and figured one place which miss NPE catching
=> adds missing NPE catch in order to handle rare racing cases

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
This PR includes extra supportive class which should be used only for requestXXX interactions via `Operators.lift` in order to simplify business logic inside `RSocketRequester` (e.g. wipLoops and `cancel` / `request` signals serialization)
***Also***, this PR, ensures that `streamId` will be generated exactly during the first request phase so we will not waste sequence in case stream was not subscribed. The same is relevant to 
```java
private final IntObjectMap<Subscription> senders;
private final IntObjectMap<Processor<Payload, Payload>> receivers;
```
holders which are going to get logical stream `put` in it only in case of successful subscription to the generated interaction with the subsequent `request(n)` call on it. 
Note. `StreamId` should not be issued until the first `requestN` …
=> provides supportive class to hide concurrency complexity

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/test/java/io/rsocket/TestScheduler.java, rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
This PR ensures that stream ids are issued in order even under high racing between logical streams in the way of scheduling stream id issuing on the event loop scheduler. 
This is done on the level of RSocket because of the incorrect Transport level design and should be considered as a workaround until DuplexConnection will be revised in 1.1
=> provides ordered stream id issuing

rsocket-core/src/main/java/io/rsocket/core/StreamIdSupplier.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
This PR is a follow up to #811 and therefore introduces a non-thread safe way to issue stream id since this class is never called in the concurrent fashion
=> relaxed stream id supplement 

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptorExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptoreExample.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
closes #825 
This PR removes usage of `limitRate` operator and provides an example of how one can provide `limitRate` just in case this is crucial
=> removes limit rate operator

rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
This PR provides `bindNow` for the RSocketServer which provides a shortcut for `bind().block` which pretty common start for the server-side
=> provides `bindNow` shortcut for the server

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/lease/ResponderLeaseHandler.java, rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java, rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
=> removes deprecated errorConsumer

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
=> fixes onClose behaviour to not error on shutdown

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/plugins/LimitRateInterceptor.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptorExample.java
Promote `LimitRateInterceptor` to rsocket-core to make it more visible and available out of the box. Although it's easy to apply `limitRate` to individual streams, the interceptor is useful for doing so consistently from a single place.
=> includes LimitRateInterceptor as a built-in interceptor

rsocket-core/src/main/java/io/rsocket/metadata/TracingMetadata.java, rsocket-core/src/main/java/io/rsocket/metadata/TracingMetadataCodec.java, rsocket-core/src/test/java/io/rsocket/metadata/TracingMetadataCodecTest.java
=> provides support for TracingMetadata

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
=> bugfix `RSocketConnector#setupPayload` to copy the content

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
closes #846 
This PR fixes the case when a new stream might have already been started but the terminal error was not put into the list, so the termination will omit that "half initiated" one so it will hang forever since UnboundedProcessor does not error when calling onNext.
As a fix, the termination operation is scheduled on the `serializedScheduler` so there is no racing between new requests and termination. Also, all the streams that were scheduled but have not observed termination do this check again on the first request method so if there is termination, this stream will be terminated immediately 
=> ensures streams are terminated if racing terminal and new stream

rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java, rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java
Found that there is a bug in ReconnectMono when it appears that `Reconnect#invalidate` is raced with `Reconnect#subscribe` method which is possible when e.g.
```
Mono<RSocket> rsocketMono =
RSocketConnector.create()
.reconnect(Retry.fixedDelay(3, Duration.ofSeconds(1)))
.connect(transport)
.flatMap(rSocket -> {
return rsocket.requestStream(...);
})
.retryWhen(Retry.backoff(10000, Duration.ofMillis(1)))
.subscribe();
```
subscriber retried, subscribed, resolved connection while the thread that invalidating RSocket has executed CAS operation and in the process of setting `this.value = null`.
In general, including a few more omitted cases, there can be 3 outcomes
1. The subscriber that observed state `RSocket is READY` can observe the actual value as null because of racing with invalidate
2. …
=> fixes ReconnectMono behaviour when racing invalidate and subscribe #847

rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/CloseableChannel.java
`DisposableChannel#address` was changed in https://github.com/reactor/reactor-netty/pull/1081 to return `SocketAddress` instead of `InetSocketAddress` in order to support UNIX domain sockets. This is a binary incompatible change resulting in a new method in `DisposableChannel` in 1.0 and using RSocket compiled against 0.9.x causes `NoSuchMethodError`.
=> Forward compatibility with Reactor Netty 1.0

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/core/DefaultRSocketClient.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java, rsocket-core/src/main/java/io/rsocket/core/ResolvingOperator.java, rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java, rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java, rsocket-core/src/test/java/io/rsocket/core/ResolvingOperatorTests.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/client/RSocketClientExample.java
This PR provides a few things (as separate commits):
1. Introduced common ResolvingOperator to simplify implementations of deferred value resolution
1. Provides Client API for RSocket class
1. Provides Default impl
=> introduces RSocketClient as way to use RSocket from the connector side

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
=> fixes ConnectionSetupPayload refcnt management

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
This PR ensures that lease is used right before when the actual request frame is being sent.
That said that right now lease is used even though the `Publisher` given as the result of the `requestXXX` method execution is not subscribed (which of course may break lease counting on the client- vs server-side)
=> ensures lease is used exactly on request frame sending

rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
=> ensures there is no extra logging about a dropped error

rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
This PR ensures that error from the responder side in the case of `requestChannel ` will terminate the responder subscriber. Also, it ensures that requester error will cancel responder publisher according to the spec
=> fixes responder to handle errors according to the spec

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
=> provides error handling in case Bubbling / NIC exceptions

rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/duplex/TaskProcessingWithServerSideNotificationsExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/fnf/TaskProcessingWithServerSideNotificationsExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/ClientStreamingToServer.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/ServerStreamingToClient.java
=> provides an example of peer to peer communication

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
Currently `RSocketConnector` expects a `Payload` instance for the SETUP frame. However, if the input is from a higher level object, it may be serialized to `Mono<Payload>`. So that needs to be resolved first, then the `setupPayload` can be set on `RSocketConnector`, and only then can `connect` be called. This makes it difficult to avoid re-creating the `Mono<RSocket>` from the connect method per subscriber, which in turn precludes use of the reconnect feature.
This change adds an extra option on `RSocketConnector` to accept a `Mono<Payload>`.
=> Add option to provide Mono<Payload> for the SETUP payload

rsocket-core/src/main/java/io/rsocket/util/DefaultPayload.java, rsocket-core/src/test/java/io/rsocket/frame/SetupFrameCodecTest.java, rsocket-core/src/test/java/io/rsocket/util/DefaultPayloadTest.java
closes #882 
This PR makes `DefaultPayload.create(ByteBuf, ByteBuf)` behaves consistent with `ByteBufPayload.create(ByteBuf, ByteBuf)` method.
Please note, both methods do not require a user to take any further actions on releasing provided data and metadata `ByteBuf`s. This is a responsibility of the Payload to do so immediately (in the case of `DefaultPayload`) or later, upon the release faze (in case of `ByteBufPayload`)
=> fixes `DefaultPayload.create(ByteBuf, ByteBuf)` to release params

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java, rsocket-core/src/test/java/io/rsocket/test/util/LocalDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/test/util/TestDuplexConnection.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java, rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalTransportWithFragmentationTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
improves ref counting and performance subsequently by eliminating redundant `retain` on the transport level hence we do not need to `release` this frame on the `RSocketRequester`/`RSocketResponder` `handleFrame` level anymore
Fixes all duplex connections to follow that strategy
=> improves ref-counting by eliminating redundant retain/release

rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/test/java/io/rsocket/core/RSocketServerTest.java, rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java
=> Reject any frames before SETUP/LEASE

rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FrameReassemblerTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
=> Reject empty fragments

build.gradle
The Travis CI build is currently relying on old reactor SNAPSHOTs and fails as a result.
This PR reduces the amount of time changing dependencies are cached between builds.
=> Re-resolve changing dependencies every 60 min

rsocket-core/src/main/java/io/rsocket/core/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-test/src/main/java/io/rsocket/test/ByteBufRepresentation.java, rsocket-test/src/main/java/io/rsocket/test/LeaksTrackingByteBufAllocator.java, rsocket-test/src/main/java/io/rsocket/test/TestRSocket.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java, rsocket-test/src/main/java/io/rsocket/test/TriFunction.java, rsocket-test/src/main/resources/META-INF/services/org.assertj.core.presentation.Representation, rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpSecureTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketSecureTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketTransportTest.java
This PR reworks `ClientServerInputMultiplexer` to avoid async enqueueing/dequeuing of the incoming frames when interceptors offload subscription/publication on the different `Scheduler`, so frame appears released at the time of its consumption (`FluxReceiver` sends `ByteBuf` and releases it once `onNext` is returned -> https://github.com/reactor/reactor-netty/blob/master/reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java#L264).
Basically this PR gets rid of `groupBy` operator in favor of its drain-free version.
***FYI. This PR as well as changes related to refCoutning mechanics brake resumability***.
It can wait since there is no usage of this feature in Spring-Messaging, though we should revise the whole resumability implementation before the final 1.1 release. …
=> reworks multiplexer and improves tests to check async interceptors #909

rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
Fixes Request Handlers to ignore all further payload fragments as well as ignore request frames which stream ID clashes with an existing ongoing streams 
=> ensures new requests with existing stream id are handled properly

rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/ReassemblyUtils.java, rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
This is essentially the fix for #895 for the 1.1 code base. The logic for re-assembling is in a different class compared to 1.0 so the fix is in a different place and not a straight forward merge.
=> Reject frames less than min MTU size

rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceStrategy.java, rsocket-core/src/main/java/io/rsocket/loadbalance/PooledWeightedRSocket.java, rsocket-core/src/main/java/io/rsocket/loadbalance/RSocketPool.java, rsocket-core/src/main/java/io/rsocket/loadbalance/RoundRobinLoadbalanceStrategy.java, rsocket-core/src/main/java/io/rsocket/loadbalance/Stats.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedRSocket.java
This PR changes LoadbalanceStrategy to accept List instead of the array
=> changes LoadbalanceStrategy to accept List

rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java, rsocket-core/src/main/java/io/rsocket/loadbalance/RoundRobinLoadbalanceStrategy.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java
The `LoadbalanceClient` builder provides methods to switch the strategy, but being able to also instantiate and pass the strategies in provides more flexibility. This comes up for loadbalance support in Spring's `RSocketRequester` builder.
=> Make LoadbalanceStrategy implementations public

rsocket-core/src/main/java/io/rsocket/DuplexConnection.java, rsocket-core/src/main/java/io/rsocket/core/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/test/util/LocalDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/test/util/TestDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/test/util/TestLocalSocketAddress.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/MicrometerDuplexConnection.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
Pull request for #735 and #743.
=> Expose remote address via DuplexConnection

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/internal/BaseDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/InMemoryResumableFramesStore.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/resume/ServerRSocketSession.java, rsocket-core/src/test/java/io/rsocket/internal/UnboundedProcessorTest.java, rsocket-test/src/main/java/io/rsocket/test/LeaksTrackingByteBufAllocator.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java, rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalResumableTransportTest.java, rsocket-transport-local/src/test/resources/logback-test.xml, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpResumableTransportTest.java, rsocket-transport-netty/src/test/resources/logback-test.xml
This PR ensures that resumability implementation is stable and does not have any mem leaks in it
=> ensures that resumability implementation is stable

rsocket-core/src/main/java/io/rsocket/metadata/AuthMetadataCodec.java, rsocket-core/src/test/java/io/rsocket/metadata/security/AuthMetadataFlyweightTest.java
Now reads/writes username length as uint16.
The spec was changed in this commit:
https://github.com/rsocket/rsocket/commit/2687daae258f3688e769dbaddb426c65d7420acd
I also moved the code of AuthMetdataFlyweightTest to AuthMetadataCodecTest.
=> updates username length to align with the spec (uint8 vs uint16)

rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
Indeed as suggested in https://github.com/rsocket/rsocket-java/issues/914#issuecomment-671742260, since the removal of an individual sending subscription is not synchronized, when iterating over all subscription we can run into null values. This change iterates explicitly and continues despite errors on a best case effort.
=> Safer iteration when cancelling subscriptions

rsocket-core/src/main/java/io/rsocket/frame/decoder/DefaultPayloadDecoder.java
Hey, folks!
This PR proposes changing `DefaultPayloadDecoder` to use on-heap buffers instead of off-heap buffers. 
The reason for this is that off-heap buffers release the underlying buffer using cleaner when [the ByteBuffer's reference is gone](https://github.com/openjdk/jdk13/blob/master/src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template#L135). Due to direct buffers, it's much harder to predict what the actual memory consumption of the app is as there are no guarantees on when the cleaner is run and when the references are actually released. Additionally, `jdk.internal.ref.Cleaner` increases the GC pressure. In our case, replacing `allocateDirect` with `allocate` resulted in a significant drop of the length of GC pauses as on the graphs below. 
In my understanding, the …
=> use heap buffers in the default payload decoder

rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java
The use of a `Builder` helps to isolate a couple of optional properties and keeps the potential to expose more of its internal parameters for configuration in the future.
=> Update WeightedLoadbalanceStrategy to use a Builder

rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java, rsocket-core/src/main/java/io/rsocket/plugins/InitializingInterceptorRegistry.java, rsocket-core/src/main/java/io/rsocket/plugins/InterceptorRegistry.java, rsocket-core/src/test/java/io/rsocket/plugins/RequestInterceptorTest.java
Avoiding the overload with `RSocketInterceptor` registrations helps to avoid ambiguity when using lambdas.
=> Rename RequestInterceptor registration methods

rsocket-core/src/main/java/io/rsocket/loadbalance/MonoDeferredResolution.java, rsocket-core/src/main/java/io/rsocket/loadbalance/PooledRSocket.java, rsocket-core/src/main/java/io/rsocket/loadbalance/RSocketPool.java, rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceTest.java, rsocket-core/src/test/java/io/rsocket/loadbalance/RoundRobinLoadbalanceStrategyTest.java, rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java
closes #716
closes #822
closes #633
=> Improves Loadbalance implementations and test coverage

rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
=> Ensure Subscriber is removed from sendingSubscriptions

rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java
fixes https://github.com/spring-cloud/spring-cloud-sleuth/issues/1789
=> fixes RequestOperator to subscribe to the source at later phase

rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceTest.java, rsocket-core/src/test/java/io/rsocket/loadbalance/RoundRobinLoadbalanceStrategyTest.java
I think, on occasion, not all requests had finished executing when the counter is checked.
=> fixes LoadbalanceTest issues

rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
closes #959 
Some fix details:
Due to the RSocket Specification, section ["Handling the unexpected"](https://github.com/rsocket/rsocket/blob/master/Protocol.md#handling-the-unexpected)
> Lack of REQUEST_N frames that stops a stream is an application concern and SHALL NOT be handled by the protocol.
the `RequestOperator` does unbounded request to the `UnicastProcessor` once in order to avoid any concurrency on the internal WIP field.
=> fixes OverflowException if UnicstProcessr request and onNext race

rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/test/java/io/rsocket/internal/UnboundedProcessorTest.java, rsocket-core/src/test/java/io/rsocket/internal/subscriber/AssertSubscriber.java
=> fixes deadlock on multiconsumer clear/poll in UnboundedProcessor

rsocket-core/src/main/java/io/rsocket/util/DefaultPayload.java, rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
The RSocketConnector method that takes a setupPayload as `Payload`, as documented, tries to make a copy of a `ByteBufPayload` in order to ensure it can be re-used (e.g. on reconnect). However, `DefaultPayload#create` wasn't really making a copy. This PR fixes that and ensures that `DefaultPayload` copies data and metadata from ByteBuf's.
This is likely a fix for #970.
=> Ensure DeafultPayload#create methods copy ByteBuf content

rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java
When one define custom mtu to be used for fragment size it significantly degrades performance. Attached example code sends 1M records with size 5 bytes. Before fix it takes 39 seconds. After fix it takes 5 seconds (same time as with no custom fragmentation). We need to enable it, because Websocket max data size is 64kB and we support both transports.
See #994
=> fixes performance degradation when fragmentation is used

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
Proposed fix for https://github.com/rsocket/rsocket-java/issues/914#issuecomment-796764967.
=> adds Null-safe iteration of active streams

rsocket-transport-netty/build.gradle
Fix resolution of `netty-tcnative-boringssl-static` artifact classifier.
On apple m1 mac, that is resolved as `osdetector.classifier="osx-aarch_64"` in gradle IntelliJ fails to import the project with diagnostics:
```
Could not find netty-tcnative-boringssl-static-2.0.36.Final-osx-aarch_64.jar (io.netty:netty-tcnative-boringssl-static:2.0.36.Final).
```
Root cause is wrong resolution of `os_suffix` variable. Fixed.
Verified on architectures: `osx-aarch_64`, `linux-x86_64`, `osx-x86_64`.
Apple M1 machines now can import the project and execute tests via gradle CLI.
=> fixes netty-tcnative-boringssl-static dependency resolution

rsocket-core/src/test/java/io/rsocket/RaceTestConstants.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java, rsocket-core/src/test/java/io/rsocket/core/ResolvingOperatorTests.java, rsocket-core/src/test/java/io/rsocket/exceptions/ExceptionsTest.java, rsocket-core/src/test/java/io/rsocket/internal/UnboundedProcessorTest.java
Makes the number of repeats of race tests as a const which can be set up through the program args 
=> makes numbers of repeats of race tests as env constant

build.gradle, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/Resume.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/InMemoryResumableFramesStore.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/resume/ServerRSocketSession.java, rsocket-core/src/test/java/io/rsocket/resume/InMemoryResumeStoreTest.java, rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java, rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalResumableWithFragmentationTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpResumableWithFragmentationTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketResumableTransportTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketResumableWithFragmentationTransportTest.java
At the moment Resumability implementation is unstable due to its non-well-covered reworked impl.
As it was uncovered, the main root-cause of the problem is the incorrect state synchronization in InMemoryResumableFrameStore when it comes to the connection reestablishment (e.g. the previous connection was lost so we need to go through the resume handshake phase). 
As it was observed, the local producers may produce more elements while the new subscriber iterating over the cached value may miss some updates.
To resolve the mentioned problem, InmemoryResumableFrameStore is reworked again with the thought of **backpressure (via ASYNC fusion)** and fully **sequentially signals processing** (using WorkInProgress pattern). 
The first improvements allow draining elements from the upfront …
=> reworks InMemoryResumableFramesStore and improves its tests coverage

rsocket-core/build.gradle, rsocket-core/src/jcstress/java/io/rsocket/core/FireAndForgetRequesterMonoStressTest.java, rsocket-core/src/jcstress/java/io/rsocket/core/RequestResponseRequesterMonoStressTest.java, rsocket-core/src/jcstress/java/io/rsocket/core/SlowFireAndForgetRequesterMonoStressTest.java, rsocket-core/src/jcstress/java/io/rsocket/core/StressSubscription.java, rsocket-core/src/jcstress/java/io/rsocket/core/TestRequesterResponderSupport.java, rsocket-core/src/jcstress/java/io/rsocket/core/UnpooledByteBufPayload.java, rsocket-core/src/main/java/io/rsocket/core/RequesterLeaseTracker.java, rsocket-test/src/main/java/io/rsocket/test/LeaksTrackingByteBufAllocator.java, rsocket-test/src/main/java/io/rsocket/test/TestDuplexConnection.java
JCStress is a proven tool for making sure correctness of concurrency model used in various places
Adds list of JCStress tests
Better verification of concurrency related issues
=> adds jcstress for requester and responder operators

.github/workflows/gradle-all.yml, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/core/SetupHandlingDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/core/RSocketServerTest.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
=> adds first frame handling timeout

build.gradle, gradle/wrapper/gradle-wrapper.properties, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
=> bumps libs versions and provides few UnboundedProcessor fixes

rsocket-core/src/main/java/io/rsocket/core/RequesterResponderSupport.java
`IntObjectMap` implements `Map` and as so it has methods:
* [`default V putIfAbsent(K key, V value)`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putIfAbsent-K-V-)
* [`default boolean remove(Object key, Object value)`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#remove-java.lang.Object-java.lang.Object-)
Those declarations uses `Object` for keys, and not specified for usage of `int` primitive as key, and as so it autobox them.
=> eliminate boxing in RequesterResponderSupport when using IntObjectMap

build.gradle, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/loadbalance/FrugalQuantile.java, rsocket-core/src/main/java/io/rsocket/loadbalance/Median.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java, rsocket-core/src/test/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategyTest.java, rsocket-core/src/test/java/io/rsocket/test/util/MockRSocket.java, rsocket-examples/build.gradle, rsocket-load-balancer/build.gradle, rsocket-load-balancer/src/test/java/io/rsocket/client/TimeoutClientTest.java
=> adds tests for WeightedLoadbalanceStrategy

build.gradle, rsocket-core/build.gradle, rsocket-core/src/jcstress/java/io/rsocket/core/StressSubscriber.java, rsocket-core/src/jcstress/java/io/rsocket/internal/UnboundedProcessorStressTest.java, rsocket-core/src/main/java/io/rsocket/core/RequestChannelRequesterFlux.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/frame/ByteBufRepresentation.java, rsocket-core/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/BaseWebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java
=> migrates from deprecated api, updates dependencies

rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/metadata/routing/CompositeMetadataExample.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/metadata/routing/RoutingMetadataExample.java
=> adds routing example with TaggingMetadata and CompositeMetadata

rsocket-core/src/main/java/io/rsocket/core/FireAndForgetRequesterMono.java, rsocket-core/src/main/java/io/rsocket/core/MetadataPushRequesterMono.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
closes #1033. Supersedes #1034  
=> fixes `block()` in MetadataPushRequesterMono/FnfRequesterMono

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
=> moves error propagation out of the synchronise to avoid deadlock

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
(cherry picked from commit 6426e45619ec32acef0c6c7184020776a9063ffe)
_[One line description of your change]_
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've done.]_
_[After your change, what will change.]_
=> moves error propagation out of the synchronise to avoid deadlock (#1060)

rsocket-core/src/main/java/io/rsocket/internal/BaseDuplexConnection.java, rsocket-test/src/main/java/io/rsocket/test/PingClient.java
Improves `BaseDuplexConnection` impl
the impl of BaseDuplexConnection is a bit awkward because of the previous iterative reimplementation of that class.
This PR makes all protected fields as final (initial goal) and rework onClose notification mechanism
=> improves BaseDuplexConnection and fixes PingClient impl

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
=> ensures setupframe is available for future use

rsocket-core/src/main/resources/META-INF/native-image/io.rsocket/rsocket-core/reflect-config.json, rsocket-transport-netty/src/main/resources/META-INF/native-image/io.rsocket/rsocket-transport-netty/reflect-config.json
The issues below are observed when trying to test rsocket native-image support 
1.
```
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex",
"	at io.rsocket.internal.jctools.queues.UnsafeAccess.fieldOffset(UnsafeAccess.java:92) ~[na:na]",
"	at io.rsocket.internal.jctools.queues.BaseMpscLinkedArrayQueueProducerFields.<clinit>(BaseMpscLinkedArrayQueue.java:53) ~[rsocket:na]",
"	... 34 common frames omitted",
"Caused by: java.lang.NoSuchFieldException: producerIndex",
"	at java.lang.Class.getDeclaredField(DynamicHub.java:968) ~[rsocket:na]",
"	at io.rsocket.internal.jctools.queues.UnsafeAccess.fieldOffset(UnsafeAccess.java:90) ~[na:na]",
"	... 35 common frames omitted",
```
2. When a `ChannelHandler` is added to the `Netty` channel pipeline, …
=> Adds reflection hints for native-image support 1.1.x

rsocket-core/src/jcstress/java/io/rsocket/core/ReconnectMonoStressTest.java, rsocket-core/src/main/java/io/rsocket/core/DefaultRSocketClient.java, rsocket-core/src/main/java/io/rsocket/core/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/core/RSocketClientAdapter.java, rsocket-core/src/main/java/io/rsocket/core/ResolvingOperator.java, rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java, rsocket-core/src/main/java/io/rsocket/loadbalance/PooledRSocket.java, rsocket-core/src/main/java/io/rsocket/loadbalance/RSocketPool.java, rsocket-core/src/main/java/io/rsocket/loadbalance/ResolvingOperator.java, rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java, rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceTest.java
=> introduces `onClose` listener for RSocketClient and `connect` method

gradle.properties, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/ObservationRequesterRSocketProxy.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/ObservationResponderRSocketProxy.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/RSocketRequesterTracingObservationHandler.java
without this change we're not taking into account a parent observation into account. Nor do we set in the reactor context the current observation for the users to use
with this change whenever an observation is being created we put it into the reacto context under a well-known micrometer.observation key (for more information look at the ObservationThreadLocalAccessor class from micrometer-core)
=> allows continuation of observations

rsocket-core/src/jcstress/java/io/rsocket/resume/InMemoryResumableFramesStoreStressTest.java, rsocket-core/src/main/java/io/rsocket/core/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-core/src/main/java/io/rsocket/core/SetupHandlingDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveHandler.java, rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/InMemoryResumableFramesStore.java, rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java, rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java, rsocket-examples/build.gradle, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
this PR ensures that `RSocket#onClose` waits until all the underlying components are closed
=> ensures `onClose` awaits all underlying components to be closed

rsocket-core/src/main/java/io/rsocket/core/DefaultRSocketClient.java, rsocket-core/src/main/java/io/rsocket/core/SendUtils.java, rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java, rsocket-core/src/test/java/io/rsocket/core/SendUtilsTest.java
=> adds class check for discarded values

rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/resume/ServerRSocketSession.java, rsocket-core/src/test/java/io/rsocket/core/RSocketServerTest.java
Ensure server setup errors are handled as described in https://github.com/rsocket/rsocket-java/issues/1092#issuecomment-2612204489.
=> Fix handling of rejected setup errors

rsocket-transport-netty/build.gradle
support netty boringssl aarch_64
Netty boringssl is available on arm64 (aarch_64)
Let's use the proper classifier.
update build.gradle
Correct artifact is observed on MacOS arm64 laptop.
=> support netty boringssl aarch_64 classifier

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-transport-netty/src/test/java/io/rsocket/integration/KeepaliveTest.java, rsocket-transport-netty/src/test/resources/logback-test.xml
=> ensures connection is closed on keepalive timeout

rsocket-core/src/main/java/io/rsocket/frame/FrameUtil.java
Ensure `FrameUtil` logs the data of KEEPALIVE frames if present.
=> Log data in KEEPALIVE frame
