src/main/java/io/reactivesocket/CancellationToken.java, src/main/java/io/reactivesocket/UnicastSubject.java, src/test/java/io/reactivesocket/UnicastSubjectTest.java
Intended for use for emitting demuxed frames per stream.
=> UnicastSubject

src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/RequestHandler.java, src/main/java/io/reactivesocket/internal/CancellationToken.java, src/main/java/io/reactivesocket/internal/FrameFlyweight.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/main/java/io/reactivesocket/internal/UnicastSubject.java, src/test/java/io/reactivesocket/FrameTest.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/RequesterResponderInteractionTest.java, src/test/java/io/reactivesocket/TestConnection.java, src/test/java/io/reactivesocket/TestUtil.java, src/test/java/io/reactivesocket/internal/RequesterTest.java, src/test/java/io/reactivesocket/internal/ResponderTest.java, src/test/java/io/reactivesocket/internal/UnicastSubjectTest.java
- unit tests passing
- working client-> server
- bidirectional is NOT working (client<->server)
- moved internal classes into .internal. package to make the public API clear (people should not interact with Responder/Requestor classes)
=> Functioning Again

src/main/java/io/reactivesocket/FrameType.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/RequestHandler.java, src/main/java/io/reactivesocket/internal/PublisherUtils.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/main/java/io/reactivesocket/internal/UnicastSubject.java, src/perf/java/io/reactivesocket/ReactiveSocketPerf.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java
Implementation of Request_Channel interaction type as per https://github.com/ReactiveSocket/reactivesocket/issues/30
=> Request_Channel

src/main/java/io/reactivesocket/Completable.java, src/main/java/io/reactivesocket/ConnectionSetupHandler.java, src/main/java/io/reactivesocket/DuplexConnection.java, src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/perf/java/io/reactivesocket/ReactiveSocketPerf.java, src/perf/java/io/reactivesocket/perfutil/PerfTestConnection.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/TestConnection.java
Improving API of ReactiveSocket and DuplexConnection.
=> API Design

src/main/java/io/reactivesocket/internal/BackpressureUtils.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/main/java/io/reactivesocket/internal/UnicastSubject.java, src/test/java/io/reactivesocket/TestConnection.java, src/test/java/io/reactivesocket/TestFlowControlRequestN.java
- requestStream and requestSubscription are working
- requestChannel is working on the downstream, not upstream yet
=> RequestN Implementation

src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/test/java/io/reactivesocket/TestFlowControlRequestN.java
- More-or-less working for both downstream and upstream.
- Very likely there are still unknown issues.
- One known issue is that we ignore REQUEST_N from the transport layer and assume it requests Long.MAX_VALUE, which it doesn't. We need to compose transport and remote REQUEST_N.
=> RequestChannel RequestN Behavior

src/test/java/io/reactivesocket/LeaseTest.java, src/test/java/io/reactivesocket/TestConnection.java
=> Wait for TestConnection

src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java, src/perf/java/io/reactivesocket/ReactiveSocketPerf.java, src/test/java/io/reactivesocket/LatchedCompletable.java, src/test/java/io/reactivesocket/LeaseTest.java, src/test/java/io/reactivesocket/ReactiveSocketTest.java, src/test/java/io/reactivesocket/RequesterResponderInteractionTest.java, src/test/java/io/reactivesocket/TestFlowControlRequestN.java, src/test/java/io/reactivesocket/internal/RequesterTest.java, src/test/java/io/reactivesocket/internal/ResponderTest.java
Allow waiting for the requester/responder to finish starting.
=> Await ReactiveSocket.start

src/main/java/io/reactivesocket/ReactiveSocket.java, src/main/java/io/reactivesocket/internal/Requester.java, src/main/java/io/reactivesocket/internal/Responder.java
=> Shutdown Hooks

src/main/java/io/reactivesocket/Frame.java, src/main/java/io/reactivesocket/internal/PayloadFragmenter.java, src/main/java/io/reactivesocket/internal/RequestFrameFlyweight.java, src/test/java/io/reactivesocket/internal/FragmenterTest.java
=> tests for fragmenter

src/main/java/io/reactivesocket/internal/PayloadReassembler.java, src/test/java/io/reactivesocket/TestUtil.java, src/test/java/io/reactivesocket/internal/ReassemblerTest.java
=> reassembler tests

reactivesocket-core/src/main/java/io/reactivesocket/ConnectionSetupPayload.java, reactivesocket-core/src/main/java/io/reactivesocket/DuplexConnection.java, reactivesocket-core/src/main/java/io/reactivesocket/RequestHandler.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/PublisherUtils.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/Responder.java, reactivesocket-core/src/main/java/io/reactivesocket/internal/UnicastSubject.java
I don't agree with Richard Hendricks to use tabs over spaces.
Gimme back my spaces.
Awesomeness .....
PS: I don't use vim or emacs... Idea rocks!
=> Tabs => Spaces

reactivesocket-client/src/main/java/io/reactivesocket/client/ClientBuilder.java, reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/DrainingSocket.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/FailureAwareFactory.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/RetrySocket.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/TimeoutFactory.java, reactivesocket-client/src/main/java/io/reactivesocket/client/filter/TimeoutSocket.java, reactivesocket-client/src/main/java/io/reactivesocket/client/stat/Ewma.java, reactivesocket-core/src/main/java/io/reactivesocket/util/ReactiveSocketFactoryProxy.java, reactivesocket-core/src/main/java/io/reactivesocket/util/ReactiveSocketProxy.java, reactivesocket-transport-tcp/src/main/java/io/reactivesocket/transport/tcp/client/TcpReactiveSocketConnector.java
***Problem***
Debuging and Logging could be improved by adding meaningful `toString()`
methods (that expose internal state).
***Solution***
Add meaningful `toString()` methods.
- Remove unused chaining functions.
- Change visibility (to protected) of the `child` factory in ReactiveSocketFactory.
=> Add meaningfull toString() methods to most objects.

reactivesocket-core/src/main/java/io/reactivesocket/internal/Requester.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/RequesterTest.java
As described in #132, All `Subscription` implementations in`Requester` were not handling the condition where a `cancel` is issued before `requestN`.
Correctly handle this condition and also short-circuit for multiple cancellations and `requestN()` post `cancel()`.
Added Unit tests to verify this for all interaction models.
No `NullPointerException`
=> Fixes #132 (Cancel before `RequestN`)

reactivesocket-core/src/main/java/io/reactivesocket/lease/FairLeaseGovernor.java, reactivesocket-examples/src/main/java/io/reactivesocket/examples/StressTest.java
***Problem***
There is a bug in FairLeaseGovernor, the number of ticket per Responder is
never decreased.
***Solution***
Fix the bug (straightforward).
Also, add two unit-tests and improve the constructor.
=> Fix bug in FairLeaseGovernor

reactivesocket-core/src/test/java/io/reactivesocket/lease/FairLeaseGovernorTest.java
I had written this test for PR #147, but failed to add it.
=> Add unit-test for FairLeaseGovernor

reactivesocket-transport-aeron/src/test/java/io/reactivesocket/aeron/internal/reactivestreams/AeronChannelTest.java, reactivesocket-transport-aeron/src/test/java/io/reactivesocket/aeron/internal/reactivestreams/AeronClientServerChannelTest.java
The test fails on travis all the time.
Ignored it for now. I am not yet clear about the reason for the failure.
Travis build should pass now and so other PRs can be validated.
=> Ignore `AeronChannelTest` and `AeronClientServerChannelTest`

reactivesocket-core/src/main/java/io/reactivesocket/lease/DefaultLeaseEnforcingSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/DefaultLeaseHonoringSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/lease/FairLeaseDistributor.java, reactivesocket-core/src/test/java/io/reactivesocket/lease/FairLeaseDistributorTest.java
This PR addresses two problems:
- Typically users of `FairLeaseDistributor` would supply the same value for lease TTL and the period in which leases are distributed. In such cases, there would be a time period when new lease has not arrived and old lease is expired. This isn't a good reflection of server's intent as the server can handle the new requests but the lease has not yet reached the client.
- New clients have to wait for the next distribution tick to get leases.
- Modified `FairLeaseDistributor` to increase user supplied lease TTL by 10% so that leases overlap. A server can still reject requests if it is overloaded.
- Redistribute leases whenever a new client connects.
Better leasing behavior as seen by the clients.
=> Overlapping leases and redistribution on new connects

reactivesocket-client/src/main/java/io/reactivesocket/client/LoadBalancer.java
__Problem__
There are the following issues:
- `removeSocket()` was not subscribing to `socket.close()`. Since, `close()` is lazy, not subscribing will not close the socket.
- Socket is not removed when it closes, unless a request is made to it.
- `refreshSocket()` only gets called when making a request. This means that if a client awaits `availability()` when load balancer does not have any active sockets (`NoAvailableHostException`), it is a deadlock as load balancer will never add a socket if there are no requests.
- Subscribe to `socket.close()`
- Added a `onClose()` listener that removes the socket from the active list when it closes.
- Call `refreshSockets()` in `removeSocket()`
__ Result__
No deadlock when awaiting availability as a reaction to …
=> LoadBalancer: remove socket on close and refresh sockets.

reactivesocket-core/src/main/java/io/reactivesocket/Frame.java, reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/KeepaliveFrameFlyweight.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/PayloadFragmenter.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/PayloadReassembler.java, reactivesocket-core/src/main/java/io/reactivesocket/frame/RequestFrameFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/KeepaliveFrameFlyweightTest.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/FragmenterTest.java, reactivesocket-core/src/test/java/io/reactivesocket/internal/ReassemblerTest.java
The common ones follow/complete can be reused for all frames.
=> Simplify frame flags

reactivesocket-core/src/jmh/java/io/reactivesocket/ReactiveSocketPerf.java
Subscription type has been killed with fire by @lexs.  Remove remnant references
=> fix requestSubscription override in 1.0.x

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java
Previously, the initialRequestN value of the REQUEST_STREAM frame was
completely ignored and 2 was used instead.  Fixing it.
Tested this by running tck against cpp version and ensuring requestN
gets propagated properly to the java-publisher.
=> Fix initialRequestN value for requestStream

reactivesocket-core/src/main/java/io/reactivesocket/frame/FrameHeaderFlyweight.java, reactivesocket-core/src/test/java/io/reactivesocket/frame/FrameHeaderFlyweightTest.java, reactivesocket-transport-netty/src/main/java/io/reactivesocket/transport/netty/ReactiveSocketLengthCodec.java
According to the spec the field size should not be included in the frame size value.
=> Fix frame size field serialization

reactivesocket-core/src/main/java/io/reactivesocket/ServerReactiveSocket.java
Addresses #271 
A RequestResponseHandler will never have to send CANCEL for response (according to spec)
=> dont send CANCEL from RequestResponseHandler

rsocket-core/src/main/java/io/rsocket/ServerRSocket.java
As specified https://github.com/rsocket/rsocket/blob/master/Protocol.md#keepalive-frame-0x03 echo the keepalive data payload in the response
=> echo keepalive data

rsocket-core/src/main/java/io/rsocket/transport/ServerTransport.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java, rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/NettyContextClosable.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/NettyContextCloseable.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
Allow TCP server to use an ephemeral port
=> ephemeral port

rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
=> Websocket uri support

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
this author tag is a one off in the repo, assume it came from Intellij
=> remove author tag

build.gradle, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-transport-aeron/src/test/java/io/rsocket/aeron/internal/reactivestreams/AeronClientServerChannelTest.java, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
Reactor 3.1.x is not compatible with Reactor 3.0.x, upgrading since there is no point targetting the older version.
=> Reactor 3.1.0.M2

.travis.yml
"PSA: Updates are coming to our sudo-enabled Trusty images! You can add `group: edge` to your .travis.yml file to test them out in advance. Stay tuned for a blog post with more details. "
=> Testing with travis trusty

rsocket-core/src/main/java/io/rsocket/Frame.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/exceptions/ApplicationException.java, rsocket-core/src/main/java/io/rsocket/exceptions/CancelException.java, rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionCloseException.java, rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionException.java, rsocket-core/src/main/java/io/rsocket/exceptions/Exceptions.java, rsocket-core/src/main/java/io/rsocket/exceptions/InvalidRequestException.java, rsocket-core/src/main/java/io/rsocket/exceptions/InvalidSetupException.java, rsocket-core/src/main/java/io/rsocket/exceptions/RSocketException.java, rsocket-core/src/main/java/io/rsocket/exceptions/RejectedException.java, rsocket-core/src/main/java/io/rsocket/exceptions/RejectedResumeException.java, rsocket-core/src/main/java/io/rsocket/exceptions/RejectedSetupException.java, rsocket-core/src/main/java/io/rsocket/exceptions/SetupException.java, rsocket-core/src/main/java/io/rsocket/exceptions/UnsupportedSetupException.java, rsocket-core/src/main/java/io/rsocket/frame/ErrorFrameFlyweight.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-core/src/test/java/io/rsocket/frame/ErrorFrameFlyweightTest.java
- Rejected resume added
- Remove metadata support from Error frames
- tests and various related fixes
=> exception handling fixes

rsocket-tck-drivers/src/test/java/io/rsocket/tckdrivers/TckTest.java
Refactor TckTest:
1) Introduced TckIndividualTest 
2) Added ExtractTests method
=> Refactor TckTest(added TckIndividualTest and ExtractTests)

rsocket-tck-drivers/build.gradle
Updated the rsocket-tck-driver/build.gradle file for io.rsocket.tckdrivers.main.Main
=> Added the tck-main file [Part 2]

rsocket-core/src/main/java/io/rsocket/Payload.java, rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java, rsocket-core/src/main/java/io/rsocket/lease/Lease.java, rsocket-load-balancer/src/main/java/io/rsocket/stat/Quantile.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/RSocketLengthCodec.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/NettyContextCloseable.java
2 minute cleanup for core packages - partially addresses https://github.com/rsocket/rsocket-java/issues/362
aeron and tck-driver are left
=> cleanup of javadoc for core packages

rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/test/util/TestSubscriber.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-load-balancer/src/main/java/io/rsocket/stat/Quantile.java, rsocket-load-balancer/src/test/java/io/rsocket/client/RSocketSupplierTest.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaClientDriver.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/TckClientTest.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/TckTestSuite.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/runner/JsonUtil.java, rsocket-tck-drivers/src/test/java/io/rsocket/tckdrivers/TckTest.java, rsocket-test/src/main/java/io/rsocket/test/TestSubscriber.java
remove deprecated API usage
remove unnecessary interface modifier
remove unused import
=> remove unnecessary code

build.gradle, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java, rsocket-core/src/test/java/io/rsocket/test/util/TestSubscriber.java, rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java, rsocket-load-balancer/src/main/java/io/rsocket/stat/Quantile.java, rsocket-load-balancer/src/test/java/io/rsocket/client/RSocketSupplierTest.java, rsocket-spectator/src/main/java/io/rsocket/spectator/SpectatorRSocket.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaClientDriver.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/TckClientTest.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/TckTestSuite.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/runner/JsonUtil.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/runner/RunnerRSocket.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/runner/TckMessageUtil.java, rsocket-tck-drivers/src/test/java/io/rsocket/tckdrivers/TckTest.java, rsocket-test/src/main/java/io/rsocket/test/TestSubscriber.java
generify return values
suppress unchecked method invocation
=> suppress unchecked method invocation

rsocket-core/src/jmh/java/io/rsocket/RSocketPerf.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java, rsocket-core/src/test/java/io/rsocket/test/util/TestSubscriber.java
unchecked warnings issued by the compiler
=> unchecked warnings

.gitattributes
add .gitattributes for normalize line ending
=> add git attributes

build.gradle, gradle.properties
Enable support for project scan
`./gradlew build --scan`
=> Gradle Scan

build.gradle, rsocket-core/src/jmh/java/io/rsocket/FragmentationPerf.java, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/frame/FrameHeaderFlyweight.java, rsocket-core/src/main/java/io/rsocket/resume/ResumeUtil.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/client/JavaClientDriver.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/ConsoleUtils.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/common/MySubscriber.java, rsocket-tck-drivers/src/main/java/io/rsocket/tckdrivers/server/JavaServerDriver.java, rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/SingleThreadedEventLoop.java, rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/reactivestreams/messages/AckConnectDecoder.java, rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/reactivestreams/messages/ConnectDecoder.java, rsocket-transport-aeron/src/main/java/io/rsocket/aeron/internal/reactivestreams/messages/VarDataEncodingDecoder.java, rsocket-transport-aeron/src/test/java/io/rsocket/aeron/internal/reactivestreams/AeronChannelPongServer.java, rsocket-transport-aeron/src/test/java/io/rsocket/aeron/internal/reactivestreams/AeronChannelTest.java
upgrade google-java-format to version 1.4
=> google-java-format 1.4

rsocket-core/src/main/java/io/rsocket/frame/VersionFlyweight.java, rsocket-core/src/test/java/io/rsocket/frame/VersionFlyweightTest.java
low effort PR :+1: . Setup frame version is decoded as negative number for values above 32k
=> version flyweight: fix short overflow bug

rsocket-core/src/main/java/io/rsocket/internal/SwitchTransform.java
Added SwitchTransform to internal, useful when you need to look at the first message on a channel before deciding how to handle it.
=> Added SwitchTransform

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/internal/SwitchTransform.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/test/java/io/rsocket/internal/UnboundedProcessorTest.java, rsocket-test/src/main/java/io/rsocket/test/BaseClientServerTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/NettyDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
SwitchTransform now uses UnboundedProcessor to prevent IllegalStateExceptions
=> SwitchTransform IllegalStateException

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/test/java/io/rsocket/RSocketTest.java
Fixes #449 by terminating subscriptions before clearing maps.
=>  Terminate subscribers before clearing map

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/SwitchTransform.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketRouteTransportTest.java
Closes #515 . Also fixed tests which assume port 8080 is available
=> Requester Channel: Cancel request on response termination

build.gradle
=> Snapshot dependency

build.gradle, gradle.properties, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java
Prepare to 0.11.9 RELEASE
* update to latest Reactor which fixes some bugs with netty transport 
=> prepare for release

rsocket-core/src/main/java/io/rsocket/internal/SwitchTransformFlux.java
=> fix release first

rsocket-core/src/main/java/io/rsocket/internal/SwitchTransformFlux.java, rsocket-core/src/test/java/io/rsocket/internal/SwitchTransformFluxTest.java
=> removed safeRelease

.gitignore, rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/StreamIdSupplier.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-load-balancer/src/main/java/io/rsocket/client/RSocketSupplierPool.java, rsocket-load-balancer/src/test/java/io/rsocket/client/LoadBalancedRSocketMonoTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/SendPublisher.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
This addresses the issue https://github.com/rsocket/rsocket-java/issues/540 where load balancer does not reconnect.
=> loadbalancer reconnects when downstream connection goes away

gradle.properties, rsocket-core/src/main/java/io/rsocket/framing/AbstractRecyclableMetadataAndDataFrame.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FrameFragmenterTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FrameReassemblerTest.java, rsocket-core/src/test/java/io/rsocket/framing/PayloadFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestChannelFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestFireAndForgetFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestResponseFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestStreamFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/SetupFrameTest.java
=> fragment properly when metadata is not present

.travis.yml
Reverts rsocket/rsocket-java#586
=> Revert "add [openjdk11] to Travis build matrix"

gradle.properties, rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java, rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java
=> added missing retain on metadata when reassembling frames

rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTest.java
=> fixes issue with requestChannel never completes if server cancels (#592)

rsocket-core/src/main/java/io/rsocket/internal/BaseDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
This PR fixes onClose weirdness
=> fixes onClose issue

rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/RSocketClient.java, rsocket-core/src/main/java/io/rsocket/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/framing/FrameType.java, rsocket-core/src/main/java/io/rsocket/internal/BaseDuplexConnection.java, rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java, rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java, rsocket-core/src/test/java/io/rsocket/RSocketClientTerminationTest.java, rsocket-core/src/test/java/io/rsocket/SetupRejectionTest.java, rsocket-core/src/test/java/io/rsocket/fragmentation/FrameFragmenterTest.java, rsocket-core/src/test/java/io/rsocket/framing/PayloadFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestChannelFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestFireAndForgetFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestResponseFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/RequestStreamFrameTest.java, rsocket-core/src/test/java/io/rsocket/framing/SetupFrameTest.java, rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java, rsocket-load-balancer/src/main/java/io/rsocket/client/RSocketSupplierPool.java, rsocket-test/src/main/java/io/rsocket/test/TransportTest.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/SendPublisher.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java
=> formatting and a fix for closing connections

rsocket-core/src/main/java/io/rsocket/frame/DataAndMetadataFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/FrameLengthFlyweight.java
=> fixing error with framing

rsocket-core/src/main/java/io/rsocket/resume/ClientResume.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/Files.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/readme.md, rsocket-examples/src/main/resources/lorem.txt
Example of warm resumption of single file transfer
=> Example of resumable file transfer

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
A client acceptor, especially if declared as a top-level class and a
singleton can also benefit from access to the ConnectionSetupPayload.
=> Client-side acceptor access to ConnectionSetupPayload

rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
Additional example on how we can treat headers in order to accept/decline WebSocket connection.
=> headers treating sample

rsocket-core/src/main/java/io/rsocket/buffer/AbstractTupleByteBuf.java, rsocket-core/src/main/java/io/rsocket/buffer/Tuple2ByteBuf.java, rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java, rsocket-core/src/main/java/io/rsocket/frame/DataAndMetadataFlyweight.java, rsocket-core/src/main/java/io/rsocket/frame/FrameLengthFlyweight.java, rsocket-core/src/test/java/io/rsocket/buffer/Tuple3ByteBufTest.java, rsocket-transport-netty/build.gradle, rsocket-transport-netty/src/test/resources/logback-test.xml
Replaces composite buffers with specialized tuple frames. Fixes earlier issue where the buffers didn't properly deal with primitives that span multiple buffers.
=> Tuple Frames

build.gradle, rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java
=> Upgrade to Reactor Dysprosium q

build.gradle
Signed-off-by: Rossen Stoyanchev <rstoyanchev@pivotal.io>
=> Upgrade to Dysprosium M3

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/frame/SetupFrameFlyweight.java, rsocket-core/src/test/java/io/rsocket/ConnectionSetupPayloadTest.java, rsocket-core/src/test/java/io/rsocket/RSocketLeaseTest.java, rsocket-core/src/test/java/io/rsocket/SetupRejectionTest.java, rsocket-core/src/test/java/io/rsocket/frame/SetupFrameFlyweightTest.java, rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java, rsocket-test/src/main/java/io/rsocket/test/TestFrames.java
closes https://github.com/rsocket/rsocket-java/issues/668
=> Setup payload: distinguish missing and empty metadata

rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java
=> ConnectionSetupPayload: expose resume flag & token

.travis.yml
This PR migrates from OracleJDK8 to OpenJDK8 builds
=> moves to OpenJDK 8 builds

rsocket-core/src/main/java/io/rsocket/metadata/RoutingMetadata.java, rsocket-core/src/main/java/io/rsocket/metadata/TaggingMetadata.java, rsocket-core/src/main/java/io/rsocket/metadata/TaggingMetadataFlyweight.java, rsocket-core/src/test/java/io/rsocket/metadata/TaggingMetadataTest.java
Routing Metadata Extension:
https://github.com/rsocket/rsocket/blob/master/Extensions/Routing.md
Changes:  TaggingMetadata, RoutingMetadata and TaggingMetadataFlyweight
=> Implement Routing Metadata Extension

rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java, rsocket-core/src/main/java/io/rsocket/buffer/Tuple2ByteBuf.java, rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java
add the missing @Override annotation
=> add @Override on override method

gradle.properties, rsocket-core/src/main/java/io/rsocket/buffer/AbstractTupleByteBuf.java
TupleByteBuf.ensureWritable should return non-writable code
=> TupleByteBuf should be non-writable

rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/BaseWebsocketServerTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java, rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPingPongIntegrationTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketRouteTransportTest.java
=> fix websockets ping/pong control frames handling

rsocket-core/src/main/java/io/rsocket/metadata/WellKnownMimeType.java
=> Fix IMAGE_GIG naming error

rsocket-core/src/main/java/io/rsocket/metadata/WellKnownMimeType.java
According to specification from https://github.com/rsocket/rsocket/blob/master/Extensions/Security/Authentication.md
=> Add MESSAGE_RSOCKET_AUTHENTICATION

rsocket-core/src/main/java/io/rsocket/metadata/WellKnownMimeType.java
Stream Data MIME Types Metadata Extension https://github.com/rsocket/rsocket/blob/master/Extensions/PerStreamDataMimeTypesDefinition.md
=> add MESSAGE_RSOCKET_MIMETYPE and MESSAGE_RSOCKET_ACCEPT_MIMETYPES

rsocket-core/src/main/java/io/rsocket/RSocketFactory.java, rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/Resume.java, rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java, rsocket-core/src/main/java/io/rsocket/resume/ExponentialBackoffResumeStrategy.java, rsocket-core/src/main/java/io/rsocket/resume/PeriodicResumeStrategy.java, rsocket-core/src/main/java/io/rsocket/resume/ResumeStrategy.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java, rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java
=> Deprecate ResumeStrategy and replace with Reactor Retry

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
This PR provides an additional check to ensure that the `refCnt` is appropriate to proceed with execution
=> provides `Payload` `refCnt` verification

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/Resume.java, rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java, rsocket-core/src/test/java/io/rsocket/core/RSocketServerFragmentationTest.java
=> Add Javadoc to RSocketConnector and RSocketServer

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java, rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/package-info.java, rsocket-core/src/main/java/io/rsocket/exceptions/package-info.java, rsocket-core/src/main/java/io/rsocket/frame/package-info.java, rsocket-core/src/main/java/io/rsocket/keepalive/package-info.java, rsocket-core/src/main/java/io/rsocket/lease/package-info.java, rsocket-core/src/main/java/io/rsocket/metadata/package-info.java, rsocket-core/src/main/java/io/rsocket/package-info.java, rsocket-core/src/main/java/io/rsocket/plugins/DuplexConnectionInterceptor.java, rsocket-core/src/main/java/io/rsocket/plugins/InitializingInterceptorRegistry.java, rsocket-core/src/main/java/io/rsocket/plugins/InterceptorRegistry.java, rsocket-core/src/main/java/io/rsocket/plugins/RSocketInterceptor.java, rsocket-core/src/main/java/io/rsocket/plugins/SocketAcceptorInterceptor.java, rsocket-core/src/main/java/io/rsocket/plugins/package-info.java, rsocket-core/src/main/java/io/rsocket/resume/package-info.java, rsocket-core/src/main/java/io/rsocket/util/package-info.java
=> Add missing package-infos and Javadoc in plugins package

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
=> fixes extra Payload release on racing complete and cancel

build.gradle, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
=> improves build.gradle tests

rsocket-transport-netty/build.gradle
=> updates reactor-netty dependencies to the new naming

rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/FragmentationUtils.java, rsocket-core/src/main/java/io/rsocket/core/ReassemblyUtils.java, rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java, rsocket-core/src/main/java/io/rsocket/core/SendUtils.java, rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java, rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java, rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-core/src/test/java/io/rsocket/core/TestRequesterResponderSupport.java, rsocket-core/src/test/java/io/rsocket/test/util/TestDuplexConnection.java
This PR adds missing tests for general reassembly of incoming payload check as well as tests related to check that reassembled payload can not exceed maxInboundPayloadSize allowance 
=> provides tests for maxInboundPayloadSize check and related fixes

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java, rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java, rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java, rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java
Pull request for #887 to disallow unbounded input.
=> Avoid queueing in UnicastProcessor receivers

rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java, rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
This is a follow-up fix with additional changes that extends the changes in 1ca3b99de8eeb7c068b6afea80f69b9939b0ec74 for #914.
=> Additional cases of map iteration and removal

rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java, rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java, rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/ClientStreamingToServer.java, rsocket-test/src/main/java/io/rsocket/test/LeaksTrackingByteBufAllocator.java
=> polishes code

rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
Current sample code is no longer available in 1.1.0
=> updates sample code in RSocketConnector Javadoc

rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedStats.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedStatsRSocketProxy.java, rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedStatsRequestInterceptor.java
Signed-off-by: Spencer Gibb sgibb@pivotal.io
=> adds proxy RSocket for WeightedStatsRequestInterceptor

rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java, rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java, rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/CloseableChannelTest.java
=> enables previously disabled tests

rsocket-core/src/main/java/io/rsocket/core/LeaseSpec.java
Fixed _maxPendingRequests_ initialisation by 0
=> fixes typo in LeaseSpec initialisation

rsocket-examples/src/test/java/io/rsocket/integration/observation/ObservationIntegrationTest.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/RSocketDocumentedObservation.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/RSocketRequesterObservationConvention.java, rsocket-micrometer/src/main/java/io/rsocket/micrometer/observation/RSocketResponderObservationConvention.java
`Observation.ObservationConvention` was changed to `ObservationConvention`
More information micrometer-metrics/micrometer#3387
- Adapt to `ObservationConvention` location change
The project build is green
=> Adapts to ObservationConvention location change

rsocket-core/build.gradle, rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java, rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceRSocketClientTest.java
=> ensures LoadbalancedRSocket select new rsocket upon re-subscription RC
